// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A request to annotate one single file, e.g. a PDF, TIFF or GIF file.
public struct AnnotateFileRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Information about the input file.
  public var inputConfig: InputConfig? = nil

  /// Required. Requested features.
  public var features: [Feature] = []

  /// Additional context that may accompany the image(s) in the file.
  public var imageContext: ImageContext? = nil

  /// Pages of the file to perform image annotation.
  ///
  /// Pages starts from 1, we assume the first page of the file is page 1.
  /// At most 5 pages are supported per request. Pages can be negative.
  ///
  /// Page 1 means the first page.
  /// Page 2 means the second page.
  /// Page -1 means the last page.
  /// Page -2 means the second to the last page.
  ///
  /// If the file is GIF instead of PDF or TIFF, page refers to GIF frames.
  ///
  /// If this field is empty, by default the service performs image annotation
  /// for the first 5 pages of the file.
  public var pages: [Swift.Int32] = []

  /// Initialize a new instance of `AnnotateFileRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotateFileRequest().with { $0.inputConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.AnnotateFileRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
