// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response to a single file annotation request. A file may contain one or more
/// images, which individually have their own responses.
public struct AnnotateFileResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Information about the file for which this response is generated.
  public var inputConfig: InputConfig? = nil

  /// Individual responses to images found within the file. This field will be
  /// empty if the `error` field is set.
  public var responses: [AnnotateImageResponse] = []

  /// This field gives the total number of pages in the file.
  public var totalPages: Swift.Int32 = Swift.Int32()

  /// If set, represents the error message for the failed request. The
  /// `responses` field will not be set in this case.
  public var error: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnnotateFileResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotateFileResponse().with { $0.inputConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputConfig = CodingKeys(stringValue: "inputConfig")
    static let responses = CodingKeys(stringValue: "responses")
    static let totalPages = CodingKeys(stringValue: "totalPages")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "inputConfig",
      "responses",
      "totalPages",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.inputConfig = try container.decodeIfPresent(InputConfig.self, forKey: .inputConfig)
    if let value = try container.decodeIfPresent([AnnotateImageResponse].self, forKey: .responses) {
      self.responses = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalPages) {
      self.totalPages = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.inputConfig, forKey: .inputConfig)
    try container.encode(self.responses, forKey: .responses)
    try container.encode(self.totalPages, forKey: .totalPages)
    try container.encodeIfPresent(self.error, forKey: .error)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.AnnotateFileResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
