// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Response to an image annotation request.
public struct AnnotateImageResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// If present, face detection has completed successfully.
  public var faceAnnotations: [FaceAnnotation] = []

  /// If present, landmark detection has completed successfully.
  public var landmarkAnnotations: [EntityAnnotation] = []

  /// If present, logo detection has completed successfully.
  public var logoAnnotations: [EntityAnnotation] = []

  /// If present, label detection has completed successfully.
  public var labelAnnotations: [EntityAnnotation] = []

  /// If present, localized object detection has completed successfully.
  /// This will be sorted descending by confidence score.
  public var localizedObjectAnnotations: [LocalizedObjectAnnotation] = []

  /// If present, text (OCR) detection has completed successfully.
  public var textAnnotations: [EntityAnnotation] = []

  /// If present, text (OCR) detection or document (OCR) text detection has
  /// completed successfully.
  /// This annotation provides the structural hierarchy for the OCR detected
  /// text.
  public var fullTextAnnotation: TextAnnotation? = nil

  /// If present, safe-search annotation has completed successfully.
  public var safeSearchAnnotation: SafeSearchAnnotation? = nil

  /// If present, image properties were extracted successfully.
  public var imagePropertiesAnnotation: ImageProperties? = nil

  /// If present, crop hints have completed successfully.
  public var cropHintsAnnotation: CropHintsAnnotation? = nil

  /// If present, web detection has completed successfully.
  public var webDetection: WebDetection? = nil

  /// If present, product search has completed successfully.
  public var productSearchResults: ProductSearchResults? = nil

  /// If set, represents the error message for the operation.
  /// Note that filled-in image annotations are guaranteed to be
  /// correct, even when `error` is set.
  public var error: GoogleRpc.Status? = nil

  /// If present, contextual information is needed to understand where this image
  /// comes from.
  public var context: ImageAnnotationContext? = nil

  /// Initialize a new instance of `AnnotateImageResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotateImageResponse().with { $0.faceAnnotations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.AnnotateImageResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
