// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for async image annotation for a list of images.
public struct AsyncBatchAnnotateImagesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Individual image annotation requests for this batch.
  public var requests: [AnnotateImageRequest] = []

  /// Required. The desired output location and metadata (e.g. format).
  public var outputConfig: OutputConfig? = nil

  /// Optional. Target project and location to make a call.
  ///
  /// Format: `projects/{project-id}/locations/{location-id}`.
  ///
  /// If no parent is specified, a region will be chosen automatically.
  ///
  /// Supported location-ids:
  ///     `us`: USA country only,
  ///     `asia`: East asia areas, like Japan, Taiwan,
  ///     `eu`: The European Union.
  ///
  /// Example: `projects/project-A/locations/eu`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The labels with user-defined metadata for the request.
  ///
  /// Label keys and values can be no longer than 63 characters
  /// (Unicode codepoints), can only contain lowercase letters, numeric
  /// characters, underscores and dashes. International characters are allowed.
  /// Label values are optional. Label keys must start with a letter.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `AsyncBatchAnnotateImagesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AsyncBatchAnnotateImagesRequest().with { $0.requests = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.vision.v1.AsyncBatchAnnotateImagesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
