// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Logical element on the page.
public struct Block: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Additional information detected for the block.
  public var property: TextAnnotation.TextProperty? = nil

  /// The bounding box for the block.
  /// The vertices are in the order of top-left, top-right, bottom-right,
  /// bottom-left. When a rotation of the bounding box is detected the rotation
  /// is represented as around the top-left corner as defined when the text is
  /// read in the 'natural' orientation.
  /// For example:
  ///
  /// * when the text is horizontal it might look like:
  ///
  ///         0----1
  ///         |    |
  ///         3----2
  ///
  /// * when it's rotated 180 degrees around the top-left corner it becomes:
  ///
  ///         2----3
  ///         |    |
  ///         1----0
  ///
  ///   and the vertex order will still be (0, 1, 2, 3).
  public var boundingBox: BoundingPoly? = nil

  /// List of paragraphs in this block (if this blocks is of type text).
  public var paragraphs: [Paragraph] = []

  /// Detected block type (text, image etc) for this block.
  public var blockType: Block.BlockType = Block.BlockType()

  /// Confidence of the OCR results on the block. Range [0, 1].
  public var confidence: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Block`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Block().with { $0.property = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let property = CodingKeys(stringValue: "property")
    static let boundingBox = CodingKeys(stringValue: "boundingBox")
    static let paragraphs = CodingKeys(stringValue: "paragraphs")
    static let blockType = CodingKeys(stringValue: "blockType")
    static let confidence = CodingKeys(stringValue: "confidence")

    static let _knownKeys: Set<Swift.String> = [
      "property",
      "boundingBox",
      "paragraphs",
      "blockType",
      "confidence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.property = try container.decodeIfPresent(
      TextAnnotation.TextProperty.self, forKey: .property)
    self.boundingBox = try container.decodeIfPresent(BoundingPoly.self, forKey: .boundingBox)
    if let value = try container.decodeIfPresent([Paragraph].self, forKey: .paragraphs) {
      self.paragraphs = value
    }
    if let value = try container.decodeIfPresent(Block.BlockType.self, forKey: .blockType) {
      self.blockType = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
      self.confidence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.property, forKey: .property)
    try container.encodeIfPresent(self.boundingBox, forKey: .boundingBox)
    try container.encode(self.paragraphs, forKey: .paragraphs)
    try container.encode(self.blockType, forKey: .blockType)
    try container.encode(self.confidence, forKey: .confidence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of a block (text, image etc) as identified by OCR.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BlockType: Codable, Equatable, Sendable {
    /// Unknown block type.
    case unknown
    /// Regular text block.
    case text
    /// Table block.
    case table
    /// Image block.
    case picture
    /// Horizontal/vertical line box.
    case ruler
    /// Barcode block.
    case barcode
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .text: return 1
      case .table: return 2
      case .picture: return 3
      case .ruler: return 4
      case .barcode: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .text: return "TEXT"
      case .table: return "TABLE"
      case .picture: return "PICTURE"
      case .ruler: return "RULER"
      case .barcode: return "BARCODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BlockType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "TEXT": self = .text
      case "TABLE": self = .table
      case "PICTURE": self = .picture
      case "RULER": self = .ruler
      case "BARCODE": self = .barcode
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BlockType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .text
      case 2: self = .table
      case 3: self = .picture
      case 4: self = .ruler
      case 5: self = .barcode
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode("UNKNOWN")
      case .text: return try container.encode("TEXT")
      case .table: return try container.encode("TABLE")
      case .picture: return try container.encode("PICTURE")
      case .ruler: return try container.encode("RULER")
      case .barcode: return try container.encode("BARCODE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.Block"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
