// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Color information consists of RGB channels, score, and the fraction of
/// the image that the color occupies in the image.
public struct ColorInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// RGB components of the color.
  public var color: GoogleType.Color? = nil

  /// Image-specific score for this color. Value in range [0, 1].
  public var score: Swift.Float = Swift.Float()

  /// The fraction of pixels the color occupies in the image.
  /// Value in range [0, 1].
  public var pixelFraction: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ColorInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ColorInfo().with { $0.color = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let color = CodingKeys(stringValue: "color")
    static let score = CodingKeys(stringValue: "score")
    static let pixelFraction = CodingKeys(stringValue: "pixelFraction")

    static let _knownKeys: Set<Swift.String> = [
      "color",
      "score",
      "pixelFraction",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.color = try container.decodeIfPresent(GoogleType.Color.self, forKey: .color)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
      self.score = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .pixelFraction) {
      self.pixelFraction = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.color, forKey: .color)
    try container.encode(self.score, forKey: .score)
    try container.encode(self.pixelFraction, forKey: .pixelFraction)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ColorInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
