// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Single crop hint that is used to generate a new crop when serving an image.
public struct CropHint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The bounding polygon for the crop region. The coordinates of the bounding
  /// box are in the original image's scale.
  public var boundingPoly: BoundingPoly? = nil

  /// Confidence of this being a salient region.  Range [0, 1].
  public var confidence: Swift.Float = Swift.Float()

  /// Fraction of importance of this salient region with respect to the original
  /// image.
  public var importanceFraction: Swift.Float = Swift.Float()

  /// Initialize a new instance of `CropHint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CropHint().with { $0.boundingPoly = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.CropHint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
