// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Set of detected entity features.
public struct EntityAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Opaque entity ID. Some IDs may be available in
  /// [Google Knowledge Graph Search
  /// API](https://developers.google.com/knowledge-graph/).
  public var mid: Swift.String = Swift.String()

  /// The language code for the locale in which the entity textual
  /// `description` is expressed.
  public var locale: Swift.String = Swift.String()

  /// Entity textual description, expressed in its `locale` language.
  public var description: Swift.String = Swift.String()

  /// Overall score of the result. Range [0, 1].
  public var score: Swift.Float = Swift.Float()

  /// **Deprecated. Use `score` instead.**
  /// The accuracy of the entity detection in an image.
  /// For example, for an image in which the "Eiffel Tower" entity is detected,
  /// this field represents the confidence that there is a tower in the query
  /// image. Range [0, 1].
  @available(*, deprecated)
  public var confidence: Swift.Float = Swift.Float()

  /// The relevancy of the ICA (Image Content Annotation) label to the
  /// image. For example, the relevancy of "tower" is likely higher to an image
  /// containing the detected "Eiffel Tower" than to an image containing a
  /// detected distant towering building, even though the confidence that
  /// there is a tower in each image may be the same. Range [0, 1].
  public var topicality: Swift.Float = Swift.Float()

  /// Image region to which this entity belongs. Not produced
  /// for `LABEL_DETECTION` features.
  public var boundingPoly: BoundingPoly? = nil

  /// The location information for the detected entity. Multiple
  /// `LocationInfo` elements can be present because one location may
  /// indicate the location of the scene in the image, and another location
  /// may indicate the location of the place where the image was taken.
  /// Location information is usually present for landmarks.
  public var locations: [LocationInfo] = []

  /// Some entities may have optional user-supplied `Property` (name/value)
  /// fields, such a score or string that qualifies the entity.
  public var properties: [Property] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EntityAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityAnnotation().with { $0.mid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mid = CodingKeys(stringValue: "mid")
    static let locale = CodingKeys(stringValue: "locale")
    static let description = CodingKeys(stringValue: "description")
    static let score = CodingKeys(stringValue: "score")
    static let confidence = CodingKeys(stringValue: "confidence")
    static let topicality = CodingKeys(stringValue: "topicality")
    static let boundingPoly = CodingKeys(stringValue: "boundingPoly")
    static let locations = CodingKeys(stringValue: "locations")
    static let properties = CodingKeys(stringValue: "properties")

    static let _knownKeys: Set<Swift.String> = [
      "mid",
      "locale",
      "description",
      "score",
      "confidence",
      "topicality",
      "boundingPoly",
      "locations",
      "properties",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mid) {
      self.mid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locale) {
      self.locale = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
      self.score = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
      self.confidence = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .topicality) {
      self.topicality = value
    }
    self.boundingPoly = try container.decodeIfPresent(BoundingPoly.self, forKey: .boundingPoly)
    if let value = try container.decodeIfPresent([LocationInfo].self, forKey: .locations) {
      self.locations = value
    }
    if let value = try container.decodeIfPresent([Property].self, forKey: .properties) {
      self.properties = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mid, forKey: .mid)
    try container.encode(self.locale, forKey: .locale)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.score, forKey: .score)
    try container.encode(self.confidence, forKey: .confidence)
    try container.encode(self.topicality, forKey: .topicality)
    try container.encodeIfPresent(self.boundingPoly, forKey: .boundingPoly)
    try container.encode(self.locations, forKey: .locations)
    try container.encode(self.properties, forKey: .properties)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.EntityAnnotation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
