// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A face annotation object contains the results of face detection.
public struct FaceAnnotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The bounding polygon around the face. The coordinates of the bounding box
  /// are in the original image's scale.
  /// The bounding box is computed to "frame" the face in accordance with human
  /// expectations. It is based on the landmarker results.
  /// Note that one or more x and/or y coordinates may not be generated in the
  /// `BoundingPoly` (the polygon will be unbounded) if only a partial face
  /// appears in the image to be annotated.
  public var boundingPoly: BoundingPoly? = nil

  /// The `fd_bounding_poly` bounding polygon is tighter than the
  /// `boundingPoly`, and encloses only the skin part of the face. Typically, it
  /// is used to eliminate the face from any image analysis that detects the
  /// "amount of skin" visible in an image. It is not based on the
  /// landmarker results, only on the initial face detection, hence
  /// the <code>fd</code> (face detection) prefix.
  public var fdBoundingPoly: BoundingPoly? = nil

  /// Detected face landmarks.
  public var landmarks: [FaceAnnotation.Landmark] = []

  /// Roll angle, which indicates the amount of clockwise/anti-clockwise rotation
  /// of the face relative to the image vertical about the axis perpendicular to
  /// the face. Range [-180,180].
  public var rollAngle: Swift.Float = Swift.Float()

  /// Yaw angle, which indicates the leftward/rightward angle that the face is
  /// pointing relative to the vertical plane perpendicular to the image. Range
  /// [-180,180].
  public var panAngle: Swift.Float = Swift.Float()

  /// Pitch angle, which indicates the upwards/downwards angle that the face is
  /// pointing relative to the image's horizontal plane. Range [-180,180].
  public var tiltAngle: Swift.Float = Swift.Float()

  /// Detection confidence. Range [0, 1].
  public var detectionConfidence: Swift.Float = Swift.Float()

  /// Face landmarking confidence. Range [0, 1].
  public var landmarkingConfidence: Swift.Float = Swift.Float()

  /// Joy likelihood.
  public var joyLikelihood: Likelihood = Likelihood()

  /// Sorrow likelihood.
  public var sorrowLikelihood: Likelihood = Likelihood()

  /// Anger likelihood.
  public var angerLikelihood: Likelihood = Likelihood()

  /// Surprise likelihood.
  public var surpriseLikelihood: Likelihood = Likelihood()

  /// Under-exposed likelihood.
  public var underExposedLikelihood: Likelihood = Likelihood()

  /// Blurred likelihood.
  public var blurredLikelihood: Likelihood = Likelihood()

  /// Headwear likelihood.
  public var headwearLikelihood: Likelihood = Likelihood()

  /// Initialize a new instance of `FaceAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FaceAnnotation().with { $0.boundingPoly = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A face-specific landmark (for example, a face feature).
  public struct Landmark: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Face landmark type.
    public var type: FaceAnnotation.Landmark.Type_ = FaceAnnotation.Landmark.Type_()

    /// Face landmark position.
    public var position: Position? = nil

    /// Initialize a new instance of `Landmark`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Landmark().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Face landmark (feature) type.
    /// Left and right are defined from the vantage of the viewer of the image
    /// without considering mirror projections typical of photos. So, `LEFT_EYE`,
    /// typically, is the person's right eye.
    public enum Type_: Codable, Equatable, Sendable {
      /// Unknown face landmark detected. Should not be filled.
      case unknownLandmark
      /// Left eye.
      case leftEye
      /// Right eye.
      case rightEye
      /// Left of left eyebrow.
      case leftOfLeftEyebrow
      /// Right of left eyebrow.
      case rightOfLeftEyebrow
      /// Left of right eyebrow.
      case leftOfRightEyebrow
      /// Right of right eyebrow.
      case rightOfRightEyebrow
      /// Midpoint between eyes.
      case midpointBetweenEyes
      /// Nose tip.
      case noseTip
      /// Upper lip.
      case upperLip
      /// Lower lip.
      case lowerLip
      /// Mouth left.
      case mouthLeft
      /// Mouth right.
      case mouthRight
      /// Mouth center.
      case mouthCenter
      /// Nose, bottom right.
      case noseBottomRight
      /// Nose, bottom left.
      case noseBottomLeft
      /// Nose, bottom center.
      case noseBottomCenter
      /// Left eye, top boundary.
      case leftEyeTopBoundary
      /// Left eye, right corner.
      case leftEyeRightCorner
      /// Left eye, bottom boundary.
      case leftEyeBottomBoundary
      /// Left eye, left corner.
      case leftEyeLeftCorner
      /// Right eye, top boundary.
      case rightEyeTopBoundary
      /// Right eye, right corner.
      case rightEyeRightCorner
      /// Right eye, bottom boundary.
      case rightEyeBottomBoundary
      /// Right eye, left corner.
      case rightEyeLeftCorner
      /// Left eyebrow, upper midpoint.
      case leftEyebrowUpperMidpoint
      /// Right eyebrow, upper midpoint.
      case rightEyebrowUpperMidpoint
      /// Left ear tragion.
      case leftEarTragion
      /// Right ear tragion.
      case rightEarTragion
      /// Left eye pupil.
      case leftEyePupil
      /// Right eye pupil.
      case rightEyePupil
      /// Forehead glabella.
      case foreheadGlabella
      /// Chin gnathion.
      case chinGnathion
      /// Chin left gonion.
      case chinLeftGonion
      /// Chin right gonion.
      case chinRightGonion
      /// Left cheek center.
      case leftCheekCenter
      /// Right cheek center.
      case rightCheekCenter
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unknownLandmark
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unknownLandmark: return 0
        case .leftEye: return 1
        case .rightEye: return 2
        case .leftOfLeftEyebrow: return 3
        case .rightOfLeftEyebrow: return 4
        case .leftOfRightEyebrow: return 5
        case .rightOfRightEyebrow: return 6
        case .midpointBetweenEyes: return 7
        case .noseTip: return 8
        case .upperLip: return 9
        case .lowerLip: return 10
        case .mouthLeft: return 11
        case .mouthRight: return 12
        case .mouthCenter: return 13
        case .noseBottomRight: return 14
        case .noseBottomLeft: return 15
        case .noseBottomCenter: return 16
        case .leftEyeTopBoundary: return 17
        case .leftEyeRightCorner: return 18
        case .leftEyeBottomBoundary: return 19
        case .leftEyeLeftCorner: return 20
        case .rightEyeTopBoundary: return 21
        case .rightEyeRightCorner: return 22
        case .rightEyeBottomBoundary: return 23
        case .rightEyeLeftCorner: return 24
        case .leftEyebrowUpperMidpoint: return 25
        case .rightEyebrowUpperMidpoint: return 26
        case .leftEarTragion: return 27
        case .rightEarTragion: return 28
        case .leftEyePupil: return 29
        case .rightEyePupil: return 30
        case .foreheadGlabella: return 31
        case .chinGnathion: return 32
        case .chinLeftGonion: return 33
        case .chinRightGonion: return 34
        case .leftCheekCenter: return 35
        case .rightCheekCenter: return 36
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unknownLandmark: return "UNKNOWN_LANDMARK"
        case .leftEye: return "LEFT_EYE"
        case .rightEye: return "RIGHT_EYE"
        case .leftOfLeftEyebrow: return "LEFT_OF_LEFT_EYEBROW"
        case .rightOfLeftEyebrow: return "RIGHT_OF_LEFT_EYEBROW"
        case .leftOfRightEyebrow: return "LEFT_OF_RIGHT_EYEBROW"
        case .rightOfRightEyebrow: return "RIGHT_OF_RIGHT_EYEBROW"
        case .midpointBetweenEyes: return "MIDPOINT_BETWEEN_EYES"
        case .noseTip: return "NOSE_TIP"
        case .upperLip: return "UPPER_LIP"
        case .lowerLip: return "LOWER_LIP"
        case .mouthLeft: return "MOUTH_LEFT"
        case .mouthRight: return "MOUTH_RIGHT"
        case .mouthCenter: return "MOUTH_CENTER"
        case .noseBottomRight: return "NOSE_BOTTOM_RIGHT"
        case .noseBottomLeft: return "NOSE_BOTTOM_LEFT"
        case .noseBottomCenter: return "NOSE_BOTTOM_CENTER"
        case .leftEyeTopBoundary: return "LEFT_EYE_TOP_BOUNDARY"
        case .leftEyeRightCorner: return "LEFT_EYE_RIGHT_CORNER"
        case .leftEyeBottomBoundary: return "LEFT_EYE_BOTTOM_BOUNDARY"
        case .leftEyeLeftCorner: return "LEFT_EYE_LEFT_CORNER"
        case .rightEyeTopBoundary: return "RIGHT_EYE_TOP_BOUNDARY"
        case .rightEyeRightCorner: return "RIGHT_EYE_RIGHT_CORNER"
        case .rightEyeBottomBoundary: return "RIGHT_EYE_BOTTOM_BOUNDARY"
        case .rightEyeLeftCorner: return "RIGHT_EYE_LEFT_CORNER"
        case .leftEyebrowUpperMidpoint: return "LEFT_EYEBROW_UPPER_MIDPOINT"
        case .rightEyebrowUpperMidpoint: return "RIGHT_EYEBROW_UPPER_MIDPOINT"
        case .leftEarTragion: return "LEFT_EAR_TRAGION"
        case .rightEarTragion: return "RIGHT_EAR_TRAGION"
        case .leftEyePupil: return "LEFT_EYE_PUPIL"
        case .rightEyePupil: return "RIGHT_EYE_PUPIL"
        case .foreheadGlabella: return "FOREHEAD_GLABELLA"
        case .chinGnathion: return "CHIN_GNATHION"
        case .chinLeftGonion: return "CHIN_LEFT_GONION"
        case .chinRightGonion: return "CHIN_RIGHT_GONION"
        case .leftCheekCenter: return "LEFT_CHEEK_CENTER"
        case .rightCheekCenter: return "RIGHT_CHEEK_CENTER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "UNKNOWN_LANDMARK": self = .unknownLandmark
        case "LEFT_EYE": self = .leftEye
        case "RIGHT_EYE": self = .rightEye
        case "LEFT_OF_LEFT_EYEBROW": self = .leftOfLeftEyebrow
        case "RIGHT_OF_LEFT_EYEBROW": self = .rightOfLeftEyebrow
        case "LEFT_OF_RIGHT_EYEBROW": self = .leftOfRightEyebrow
        case "RIGHT_OF_RIGHT_EYEBROW": self = .rightOfRightEyebrow
        case "MIDPOINT_BETWEEN_EYES": self = .midpointBetweenEyes
        case "NOSE_TIP": self = .noseTip
        case "UPPER_LIP": self = .upperLip
        case "LOWER_LIP": self = .lowerLip
        case "MOUTH_LEFT": self = .mouthLeft
        case "MOUTH_RIGHT": self = .mouthRight
        case "MOUTH_CENTER": self = .mouthCenter
        case "NOSE_BOTTOM_RIGHT": self = .noseBottomRight
        case "NOSE_BOTTOM_LEFT": self = .noseBottomLeft
        case "NOSE_BOTTOM_CENTER": self = .noseBottomCenter
        case "LEFT_EYE_TOP_BOUNDARY": self = .leftEyeTopBoundary
        case "LEFT_EYE_RIGHT_CORNER": self = .leftEyeRightCorner
        case "LEFT_EYE_BOTTOM_BOUNDARY": self = .leftEyeBottomBoundary
        case "LEFT_EYE_LEFT_CORNER": self = .leftEyeLeftCorner
        case "RIGHT_EYE_TOP_BOUNDARY": self = .rightEyeTopBoundary
        case "RIGHT_EYE_RIGHT_CORNER": self = .rightEyeRightCorner
        case "RIGHT_EYE_BOTTOM_BOUNDARY": self = .rightEyeBottomBoundary
        case "RIGHT_EYE_LEFT_CORNER": self = .rightEyeLeftCorner
        case "LEFT_EYEBROW_UPPER_MIDPOINT": self = .leftEyebrowUpperMidpoint
        case "RIGHT_EYEBROW_UPPER_MIDPOINT": self = .rightEyebrowUpperMidpoint
        case "LEFT_EAR_TRAGION": self = .leftEarTragion
        case "RIGHT_EAR_TRAGION": self = .rightEarTragion
        case "LEFT_EYE_PUPIL": self = .leftEyePupil
        case "RIGHT_EYE_PUPIL": self = .rightEyePupil
        case "FOREHEAD_GLABELLA": self = .foreheadGlabella
        case "CHIN_GNATHION": self = .chinGnathion
        case "CHIN_LEFT_GONION": self = .chinLeftGonion
        case "CHIN_RIGHT_GONION": self = .chinRightGonion
        case "LEFT_CHEEK_CENTER": self = .leftCheekCenter
        case "RIGHT_CHEEK_CENTER": self = .rightCheekCenter
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unknownLandmark
        case 1: self = .leftEye
        case 2: self = .rightEye
        case 3: self = .leftOfLeftEyebrow
        case 4: self = .rightOfLeftEyebrow
        case 5: self = .leftOfRightEyebrow
        case 6: self = .rightOfRightEyebrow
        case 7: self = .midpointBetweenEyes
        case 8: self = .noseTip
        case 9: self = .upperLip
        case 10: self = .lowerLip
        case 11: self = .mouthLeft
        case 12: self = .mouthRight
        case 13: self = .mouthCenter
        case 14: self = .noseBottomRight
        case 15: self = .noseBottomLeft
        case 16: self = .noseBottomCenter
        case 17: self = .leftEyeTopBoundary
        case 18: self = .leftEyeRightCorner
        case 19: self = .leftEyeBottomBoundary
        case 20: self = .leftEyeLeftCorner
        case 21: self = .rightEyeTopBoundary
        case 22: self = .rightEyeRightCorner
        case 23: self = .rightEyeBottomBoundary
        case 24: self = .rightEyeLeftCorner
        case 25: self = .leftEyebrowUpperMidpoint
        case 26: self = .rightEyebrowUpperMidpoint
        case 27: self = .leftEarTragion
        case 28: self = .rightEarTragion
        case 29: self = .leftEyePupil
        case 30: self = .rightEyePupil
        case 31: self = .foreheadGlabella
        case 32: self = .chinGnathion
        case 33: self = .chinLeftGonion
        case 34: self = .chinRightGonion
        case 35: self = .leftCheekCenter
        case 36: self = .rightCheekCenter
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unknownLandmark: return try container.encode(0)
        case .leftEye: return try container.encode(1)
        case .rightEye: return try container.encode(2)
        case .leftOfLeftEyebrow: return try container.encode(3)
        case .rightOfLeftEyebrow: return try container.encode(4)
        case .leftOfRightEyebrow: return try container.encode(5)
        case .rightOfRightEyebrow: return try container.encode(6)
        case .midpointBetweenEyes: return try container.encode(7)
        case .noseTip: return try container.encode(8)
        case .upperLip: return try container.encode(9)
        case .lowerLip: return try container.encode(10)
        case .mouthLeft: return try container.encode(11)
        case .mouthRight: return try container.encode(12)
        case .mouthCenter: return try container.encode(13)
        case .noseBottomRight: return try container.encode(14)
        case .noseBottomLeft: return try container.encode(15)
        case .noseBottomCenter: return try container.encode(16)
        case .leftEyeTopBoundary: return try container.encode(17)
        case .leftEyeRightCorner: return try container.encode(18)
        case .leftEyeBottomBoundary: return try container.encode(19)
        case .leftEyeLeftCorner: return try container.encode(20)
        case .rightEyeTopBoundary: return try container.encode(21)
        case .rightEyeRightCorner: return try container.encode(22)
        case .rightEyeBottomBoundary: return try container.encode(23)
        case .rightEyeLeftCorner: return try container.encode(24)
        case .leftEyebrowUpperMidpoint: return try container.encode(25)
        case .rightEyebrowUpperMidpoint: return try container.encode(26)
        case .leftEarTragion: return try container.encode(27)
        case .rightEarTragion: return try container.encode(28)
        case .leftEyePupil: return try container.encode(29)
        case .rightEyePupil: return try container.encode(30)
        case .foreheadGlabella: return try container.encode(31)
        case .chinGnathion: return try container.encode(32)
        case .chinLeftGonion: return try container.encode(33)
        case .chinRightGonion: return try container.encode(34)
        case .leftCheekCenter: return try container.encode(35)
        case .rightCheekCenter: return try container.encode(36)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.vision.v1.FaceAnnotation.Landmark"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.vision.v1.FaceAnnotation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
