// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The Google Cloud Storage location where the output will be written to.
public struct GcsDestination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Google Cloud Storage URI prefix where the results will be stored. Results
  /// will be in JSON format and preceded by its corresponding input URI prefix.
  /// This field can either represent a gcs file prefix or gcs directory. In
  /// either case, the uri should be unique because in order to get all of the
  /// output files, you will need to do a wildcard gcs search on the uri prefix
  /// you provide.
  ///
  /// Examples:
  ///
  /// *    File Prefix: gs://bucket-name/here/filenameprefix   The output files
  /// will be created in gs://bucket-name/here/ and the names of the
  /// output files will begin with "filenameprefix".
  ///
  /// *    Directory Prefix: gs://bucket-name/some/location/   The output files
  /// will be created in gs://bucket-name/some/location/ and the names of the
  /// output files could be anything because there was no filename prefix
  /// specified.
  ///
  /// If multiple outputs, each response is still AnnotateFileResponse, each of
  /// which contains some subset of the full list of AnnotateImageResponse.
  /// Multiple outputs can happen if, for example, the output JSON is too large
  /// and overflows into multiple sharded files.
  public var uri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcsDestination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsDestination().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uri = CodingKeys(stringValue: "uri")

    static let _knownKeys: Set<Swift.String> = [
      "uri"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.GcsDestination"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
