// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Image context and/or feature-specific parameters.
public struct ImageContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Not used.
  public var latLongRect: LatLongRect? = nil

  /// List of languages to use for TEXT_DETECTION. In most cases, an empty value
  /// yields the best results since it enables automatic language detection. For
  /// languages based on the Latin alphabet, setting `language_hints` is not
  /// needed. In rare cases, when the language of the text in the image is known,
  /// setting a hint will help get better results (although it will be a
  /// significant hindrance if the hint is wrong). Text detection returns an
  /// error if one or more of the specified languages is not one of the
  /// [supported languages](https://cloud.google.com/vision/docs/languages).
  public var languageHints: [Swift.String] = []

  /// Parameters for crop hints annotation request.
  public var cropHintsParams: CropHintsParams? = nil

  /// Parameters for product search.
  public var productSearchParams: ProductSearchParams? = nil

  /// Parameters for web detection.
  public var webDetectionParams: WebDetectionParams? = nil

  /// Parameters for text detection and document text detection.
  public var textDetectionParams: TextDetectionParams? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageContext().with { $0.latLongRect = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let latLongRect = CodingKeys(stringValue: "latLongRect")
    static let languageHints = CodingKeys(stringValue: "languageHints")
    static let cropHintsParams = CodingKeys(stringValue: "cropHintsParams")
    static let productSearchParams = CodingKeys(stringValue: "productSearchParams")
    static let webDetectionParams = CodingKeys(stringValue: "webDetectionParams")
    static let textDetectionParams = CodingKeys(stringValue: "textDetectionParams")

    static let _knownKeys: Set<Swift.String> = [
      "latLongRect",
      "languageHints",
      "cropHintsParams",
      "productSearchParams",
      "webDetectionParams",
      "textDetectionParams",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.latLongRect = try container.decodeIfPresent(LatLongRect.self, forKey: .latLongRect)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languageHints) {
      self.languageHints = value
    }
    self.cropHintsParams = try container.decodeIfPresent(
      CropHintsParams.self, forKey: .cropHintsParams)
    self.productSearchParams = try container.decodeIfPresent(
      ProductSearchParams.self, forKey: .productSearchParams)
    self.webDetectionParams = try container.decodeIfPresent(
      WebDetectionParams.self, forKey: .webDetectionParams)
    self.textDetectionParams = try container.decodeIfPresent(
      TextDetectionParams.self, forKey: .textDetectionParams)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.latLongRect, forKey: .latLongRect)
    try container.encode(self.languageHints, forKey: .languageHints)
    try container.encodeIfPresent(self.cropHintsParams, forKey: .cropHintsParams)
    try container.encodeIfPresent(self.productSearchParams, forKey: .productSearchParams)
    try container.encodeIfPresent(self.webDetectionParams, forKey: .webDetectionParams)
    try container.encodeIfPresent(self.textDetectionParams, forKey: .textDetectionParams)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ImageContext"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
