// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ImageAnnotatorLogging: ImageAnnotatorStub {
    let inner: any ImageAnnotatorStub
    let logger: Logger

    public init(_ inner: any ImageAnnotatorStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-vision-v1"
      logger[metadataKey: "gcp.client.service"] = "vision"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ImageAnnotator"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func batchAnnotateImages(
      request: BatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchAnnotateImages",
        action: {
          (r: BatchAnnotateImagesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVisionV1.BatchAnnotateImagesResponse
          in
          return try await self.inner.batchAnnotateImages(request: r, options: o)
        })
    }

    public func batchAnnotateFiles(
      request: BatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchAnnotateFiles",
        action: {
          (r: BatchAnnotateFilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVisionV1.BatchAnnotateFilesResponse
          in
          return try await self.inner.batchAnnotateFiles(request: r, options: o)
        })
    }

    public func asyncBatchAnnotateImages(
      request: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "asyncBatchAnnotateImages",
        action: {
          (r: AsyncBatchAnnotateImagesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.asyncBatchAnnotateImages(request: r, options: o)
        })
    }

    public func asyncBatchAnnotateFiles(
      request: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "asyncBatchAnnotateFiles",
        action: {
          (r: AsyncBatchAnnotateFilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.asyncBatchAnnotateFiles(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
