// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleGax

extension Clients {
  protocol ImageAnnotatorStub: Sendable {
    func batchAnnotateImages(
      request: BatchAnnotateImagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse

    func batchAnnotateFiles(
      request: BatchAnnotateFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse

    func asyncBatchAnnotateImages(
      request: AsyncBatchAnnotateImagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func asyncBatchAnnotateFiles(
      request: AsyncBatchAnnotateFilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
