// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service that performs Google Cloud Vision API detection tasks over client
/// images, such as face, landmark, logo, label, and text detection. The
/// ImageAnnotator service returns detected entities from the images.
///
/// @Snippet(path: "ImageAnnotatorQuickstart")
public class ImageAnnotatorClient: Clients.ImageAnnotatorProtocol {
  let inner: any Clients.ImageAnnotatorStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ImageAnnotatorClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ImageAnnotatorStub = try Clients.ImageAnnotatorTransport(options)
    inner = Clients.ImageAnnotatorRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ImageAnnotatorLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Run image detection and annotation for a batch of images.
  ///
  /// @Snippet(path: "ImageAnnotator_BatchAnnotateImages")
  public func batchAnnotateImages(
    request: BatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse {
    try await self.inner.batchAnnotateImages(request: request, options: options)
  }

  /// Service that performs image detection and annotation for a batch of files.
  /// Now only "application/pdf", "image/tiff" and "image/gif" are supported.
  ///
  /// This service will extract at most 5 (customers can specify which 5 in
  /// AnnotateFileRequest.pages) frames (gif) or pages (pdf or tiff) from each
  /// file provided and perform detection and annotation for each image
  /// extracted.
  ///
  /// @Snippet(path: "ImageAnnotator_BatchAnnotateFiles")
  public func batchAnnotateFiles(
    request: BatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse {
    try await self.inner.batchAnnotateFiles(request: request, options: options)
  }

  /// Run asynchronous image detection and annotation for a list of images.
  ///
  /// Progress and results can be retrieved through the
  /// `google.longrunning.Operations` interface.
  /// `Operation.metadata` contains `OperationMetadata` (metadata).
  /// `Operation.response` contains `AsyncBatchAnnotateImagesResponse` (results).
  ///
  /// This service will write image annotation outputs to json files in customer
  /// GCS bucket, each json file containing BatchAnnotateImagesResponse proto.
  ///
  /// @Snippet(path: "ImageAnnotator_AsyncBatchAnnotateImages")
  public func asyncBatchAnnotateImages(
    request: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.asyncBatchAnnotateImages(request: request, options: options)
  }

  /// Run asynchronous image detection and annotation for a list of images.
  ///
  /// Progress and results can be retrieved through the
  /// `google.longrunning.Operations` interface.
  /// `Operation.metadata` contains `OperationMetadata` (metadata).
  /// `Operation.response` contains `AsyncBatchAnnotateImagesResponse` (results).
  ///
  /// This service will write image annotation outputs to json files in customer
  /// GCS bucket, each json file containing BatchAnnotateImagesResponse proto.
  ///
  /// @Snippet(path: "ImageAnnotator_AsyncBatchAnnotateImages")
  public func asyncBatchAnnotateImages(
    withPolling: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateImagesResponse>.State in
      return try op._extractStatus(AsyncBatchAnnotateImagesResponse.self)
    }
    let rawOp = try await self.asyncBatchAnnotateImages(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateImagesResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Run asynchronous image detection and annotation for a list of generic
  /// files, such as PDF files, which may contain multiple pages and multiple
  /// images per page. Progress and results can be retrieved through the
  /// `google.longrunning.Operations` interface.
  /// `Operation.metadata` contains `OperationMetadata` (metadata).
  /// `Operation.response` contains `AsyncBatchAnnotateFilesResponse` (results).
  ///
  /// @Snippet(path: "ImageAnnotator_AsyncBatchAnnotateFiles")
  public func asyncBatchAnnotateFiles(
    request: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.asyncBatchAnnotateFiles(request: request, options: options)
  }

  /// Run asynchronous image detection and annotation for a list of generic
  /// files, such as PDF files, which may contain multiple pages and multiple
  /// images per page. Progress and results can be retrieved through the
  /// `google.longrunning.Operations` interface.
  /// `Operation.metadata` contains `OperationMetadata` (metadata).
  /// `Operation.response` contains `AsyncBatchAnnotateFilesResponse` (results).
  ///
  /// @Snippet(path: "ImageAnnotator_AsyncBatchAnnotateFiles")
  public func asyncBatchAnnotateFiles(
    withPolling: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateFilesResponse>.State in
      return try op._extractStatus(AsyncBatchAnnotateFilesResponse.self)
    }
    let rawOp = try await self.asyncBatchAnnotateFiles(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateFilesResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ImageAnnotator_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ImageAnnotatorClient`.
  ///
  /// To mock `ImageAnnotatorClient` change your functions to receive
  /// `some ImageAnnotatorProtocol` or `any ImageAnnotatorProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ImageAnnotatorProtocol {
    /// See `ImageAnnotatorClient.batchAnnotateImages`.
    func batchAnnotateImages(request: BatchAnnotateImagesRequest) async throws
      -> GoogleCloudVisionV1.BatchAnnotateImagesResponse

    /// See `ImageAnnotatorClient.batchAnnotateImages`.
    func batchAnnotateImages(
      requests: [AnnotateImageRequest],
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse

    /// See `ImageAnnotatorClient.batchAnnotateFiles`.
    func batchAnnotateFiles(request: BatchAnnotateFilesRequest) async throws
      -> GoogleCloudVisionV1.BatchAnnotateFilesResponse

    /// See `ImageAnnotatorClient.batchAnnotateFiles`.
    func batchAnnotateFiles(
      requests: [AnnotateFileRequest],
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse

    /// See `ImageAnnotatorClient.asyncBatchAnnotateImages`.
    func asyncBatchAnnotateImages(request: AsyncBatchAnnotateImagesRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ImageAnnotatorClient.asyncBatchAnnotateImages`.
    func asyncBatchAnnotateImages(withPolling: AsyncBatchAnnotateImagesRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse>

    /// See `ImageAnnotatorClient.asyncBatchAnnotateImages`.
    func asyncBatchAnnotateImages(
      requests: [AnnotateImageRequest],
      outputConfig: OutputConfig?,
    ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse>

    /// See `ImageAnnotatorClient.asyncBatchAnnotateFiles`.
    func asyncBatchAnnotateFiles(request: AsyncBatchAnnotateFilesRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ImageAnnotatorClient.asyncBatchAnnotateFiles`.
    func asyncBatchAnnotateFiles(withPolling: AsyncBatchAnnotateFilesRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse>

    /// See `ImageAnnotatorClient.asyncBatchAnnotateFiles`.
    func asyncBatchAnnotateFiles(
      requests: [AsyncAnnotateFileRequest],
    ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse>

    /// See `ImageAnnotatorClient.batchAnnotateImages`.
    func batchAnnotateImages(
      request: BatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse

    /// See `ImageAnnotatorClient.batchAnnotateFiles`.
    func batchAnnotateFiles(
      request: BatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse

    /// See `ImageAnnotatorClient.asyncBatchAnnotateImages`.
    func asyncBatchAnnotateImages(
      request: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ImageAnnotatorClient.asyncBatchAnnotateImages`.
    func asyncBatchAnnotateImages(
      withPolling: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse>

    /// See `ImageAnnotatorClient.asyncBatchAnnotateFiles`.
    func asyncBatchAnnotateFiles(
      request: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ImageAnnotatorClient.asyncBatchAnnotateFiles`.
    func asyncBatchAnnotateFiles(
      withPolling: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse>
  }
}

// Default implementations
extension Clients.ImageAnnotatorProtocol {
  public func batchAnnotateImages(request: BatchAnnotateImagesRequest) async throws
    -> GoogleCloudVisionV1.BatchAnnotateImagesResponse
  {
    try await self.batchAnnotateImages(request: request, options: .init())
  }

  public func batchAnnotateImages(
    request: BatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchAnnotateImages(
    requests: [AnnotateImageRequest],
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateImagesResponse {
    let request = BatchAnnotateImagesRequest().with {
      $0.requests = requests
    }
    return try await self.batchAnnotateImages(request: request)
  }

  public func batchAnnotateFiles(request: BatchAnnotateFilesRequest) async throws
    -> GoogleCloudVisionV1.BatchAnnotateFilesResponse
  {
    try await self.batchAnnotateFiles(request: request, options: .init())
  }

  public func batchAnnotateFiles(
    request: BatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchAnnotateFiles(
    requests: [AnnotateFileRequest],
  ) async throws -> GoogleCloudVisionV1.BatchAnnotateFilesResponse {
    let request = BatchAnnotateFilesRequest().with {
      $0.requests = requests
    }
    return try await self.batchAnnotateFiles(request: request)
  }

  public func asyncBatchAnnotateImages(request: AsyncBatchAnnotateImagesRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.asyncBatchAnnotateImages(request: request, options: .init())
  }

  public func asyncBatchAnnotateImages(
    request: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func asyncBatchAnnotateImages(withPolling: AsyncBatchAnnotateImagesRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse>
  {
    try await self.asyncBatchAnnotateImages(withPolling: withPolling, options: .init())
  }

  public func asyncBatchAnnotateImages(
    withPolling: AsyncBatchAnnotateImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateImagesResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func asyncBatchAnnotateImages(
    requests: [AnnotateImageRequest],
    outputConfig: OutputConfig?,
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateImagesResponse> {
    let request = AsyncBatchAnnotateImagesRequest().with {
      $0.requests = requests
      $0.outputConfig = outputConfig
    }
    return try await self.asyncBatchAnnotateImages(withPolling: request)
  }

  public func asyncBatchAnnotateFiles(request: AsyncBatchAnnotateFilesRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.asyncBatchAnnotateFiles(request: request, options: .init())
  }

  public func asyncBatchAnnotateFiles(
    request: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func asyncBatchAnnotateFiles(withPolling: AsyncBatchAnnotateFilesRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse>
  {
    try await self.asyncBatchAnnotateFiles(withPolling: withPolling, options: .init())
  }

  public func asyncBatchAnnotateFiles(
    withPolling: AsyncBatchAnnotateFilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AsyncBatchAnnotateFilesResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func asyncBatchAnnotateFiles(
    requests: [AsyncAnnotateFileRequest],
  ) async throws -> any GoogleCloudGax.PollableOperation<AsyncBatchAnnotateFilesResponse> {
    let request = AsyncBatchAnnotateFilesRequest().with {
      $0.requests = requests
    }
    return try await self.asyncBatchAnnotateFiles(withPolling: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
