// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The desired output location and metadata.
public struct OutputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Google Cloud Storage location to write the output(s) to.
  public var gcsDestination: GcsDestination? = nil

  /// The max number of response protos to put into each output JSON file on
  /// Google Cloud Storage.
  /// The valid range is [1, 100]. If not specified, the default value is 20.
  ///
  /// For example, for one pdf file with 100 pages, 100 response protos will
  /// be generated. If `batch_size` = 20, then 5 json files each
  /// containing 20 response protos will be written under the prefix
  /// `gcs_destination`.`uri`.
  ///
  /// Currently, batch_size only applies to GcsDestination, with potential future
  /// support for other output configurations.
  public var batchSize: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `OutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OutputConfig().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.vision.v1.OutputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
