// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ProductSearchTransport: ProductSearchStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://vision.googleapis.com",
      )
    }

    public func createProductSet(
      request: CreateProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/productSets"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.productSetId, prefix: "productSetId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.productSet {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudVisionV1.ProductSet.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listProductSets(
      request: ListProductSetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductSetsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/productSets"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ListProductSetsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getProductSet(
      request: GetProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ProductSet.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateProductSet(
      request: UpdateProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.productSet.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "product_set.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.productSet.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "product_set.name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.productSet {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudVisionV1.ProductSet.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteProductSet(
      request: DeleteProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createProduct(
      request: CreateProductRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/products"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.productId, prefix: "productId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.product {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudVisionV1.Product.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listProducts(
      request: ListProductsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/products"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ListProductsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getProduct(
      request: GetProductRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/products/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.Product.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateProduct(
      request: UpdateProductRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.product.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard,
              ],
              fieldName: "product.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.product.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard,
            ],
            fieldName: "product.name",
            expecting: "projects/*/locations/*/products/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.product {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudVisionV1.Product.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteProduct(
      request: DeleteProductRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/products/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createReferenceImage(
      request: CreateReferenceImageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/referenceImages"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.referenceImageId, prefix: "referenceImageId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/products/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.referenceImage {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudVisionV1.ReferenceImage.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteReferenceImage(
      request: DeleteReferenceImageRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard, .literal("/referenceImages/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard, .literal("/referenceImages/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/products/*/referenceImages/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listReferenceImages(
      request: ListReferenceImagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/referenceImages"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/products/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ListReferenceImagesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getReferenceImage(
      request: GetReferenceImageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/products/"), .singleWildcard, .literal("/referenceImages/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/products/"), .singleWildcard, .literal("/referenceImages/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/products/*/referenceImages/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ReferenceImage.self, timeout: options.attemptTimeout
      ).get()
    }

    public func addProductToProductSet(
      request: AddProductToProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):addProduct"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func removeProductFromProductSet(
      request: RemoveProductFromProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):removeProduct"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listProductsInProductSet(
      request: ListProductsInProductSetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/productSets/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/products"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/productSets/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/productSets/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudVisionV1.ListProductsInProductSetResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func importProductSets(
      request: ImportProductSetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/productSets:import"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["parent"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func purgeProducts(
      request: PurgeProductsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/products:purge"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["parent"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [.literal("operations/"), .singleWildcard],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("locations/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/operations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [.literal("operations/"), .singleWildcard],
            fieldName: "name",
            expecting: "operations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("locations/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
