// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// Manages Products and ProductSets of reference images for use in product
/// search. It uses the following resource model:
///
/// - The API has a collection of [ProductSet][google.cloud.vision.v1.ProductSet]
/// resources, named `projects/*/locations/*/productSets/*`, which acts as a way
/// to put different products into groups to limit identification.
///
/// In parallel,
///
/// - The API has a collection of [Product][google.cloud.vision.v1.Product]
/// resources, named
///   `projects/*/locations/*/products/*`
///
/// - Each [Product][google.cloud.vision.v1.Product] has a collection of
/// [ReferenceImage][google.cloud.vision.v1.ReferenceImage] resources, named
///   `projects/*/locations/*/products/*/referenceImages/*`
///
/// [google.cloud.vision.v1.Product]: <doc:Product>
/// [google.cloud.vision.v1.ProductSet]: <doc:ProductSet>
/// [google.cloud.vision.v1.ReferenceImage]: <doc:ReferenceImage>
///
/// @Snippet(path: "ProductSearchQuickstart")
public class ProductSearchClient: Clients.ProductSearchProtocol {
  let inner: any Clients.ProductSearchStub

  /// Creates a new `ProductSearchClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ProductSearchStub = try Clients.ProductSearchTransport(options)
    inner = Clients.ProductSearchRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ProductSearchLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates and returns a new ProductSet resource.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if display_name is missing, or is longer than
  ///   4096 characters.
  ///
  /// @Snippet(path: "ProductSearch_CreateProductSet")
  public func createProductSet(
    request: CreateProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    try await self.inner.createProductSet(request: request, options: options)
  }

  /// Lists ProductSets in an unspecified order.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100, or less
  ///   than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProductSets")
  public func listProductSets(
    request: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductSetsResponse {
    try await self.inner.listProductSets(request: request, options: options)
  }

  /// Lists ProductSets in an unspecified order.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100, or less
  ///   than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProductSets")
  public func listProductSets(
    byItem: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProductSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductSetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProductSets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information associated with a ProductSet.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the ProductSet does not exist.
  ///
  /// @Snippet(path: "ProductSearch_GetProductSet")
  public func getProductSet(
    request: GetProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    try await self.inner.getProductSet(request: request, options: options)
  }

  /// Makes changes to a ProductSet resource.
  /// Only display_name can be updated currently.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the ProductSet does not exist.
  /// * Returns INVALID_ARGUMENT if display_name is present in update_mask but
  ///   missing from the request or longer than 4096 characters.
  ///
  /// @Snippet(path: "ProductSearch_UpdateProductSet")
  public func updateProductSet(
    request: UpdateProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    try await self.inner.updateProductSet(request: request, options: options)
  }

  /// Permanently deletes a ProductSet. Products and ReferenceImages in the
  /// ProductSet are not deleted.
  ///
  /// The actual image files are not deleted from Google Cloud Storage.
  ///
  /// @Snippet(path: "ProductSearch_DeleteProductSet")
  public func deleteProductSet(
    request: DeleteProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteProductSet(request: request, options: options)
  }

  /// Creates and returns a new product resource.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if display_name is missing or longer than 4096
  ///   characters.
  /// * Returns INVALID_ARGUMENT if description is longer than 4096 characters.
  /// * Returns INVALID_ARGUMENT if product_category is missing or invalid.
  ///
  /// @Snippet(path: "ProductSearch_CreateProduct")
  public func createProduct(
    request: CreateProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    try await self.inner.createProduct(request: request, options: options)
  }

  /// Lists products in an unspecified order.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100 or less than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProducts")
  public func listProducts(
    request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductsResponse {
    try await self.inner.listProducts(request: request, options: options)
  }

  /// Lists products in an unspecified order.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100 or less than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProducts")
  public func listProducts(
    byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProducts(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information associated with a Product.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the Product does not exist.
  ///
  /// @Snippet(path: "ProductSearch_GetProduct")
  public func getProduct(
    request: GetProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    try await self.inner.getProduct(request: request, options: options)
  }

  /// Makes changes to a Product resource.
  /// Only the `display_name`, `description`, and `labels` fields can be updated
  /// right now.
  ///
  /// If labels are updated, the change will not be reflected in queries until
  /// the next index time.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the Product does not exist.
  /// * Returns INVALID_ARGUMENT if display_name is present in update_mask but is
  ///   missing from the request or longer than 4096 characters.
  /// * Returns INVALID_ARGUMENT if description is present in update_mask but is
  ///   longer than 4096 characters.
  /// * Returns INVALID_ARGUMENT if product_category is present in update_mask.
  ///
  /// @Snippet(path: "ProductSearch_UpdateProduct")
  public func updateProduct(
    request: UpdateProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    try await self.inner.updateProduct(request: request, options: options)
  }

  /// Permanently deletes a product and its reference images.
  ///
  /// Metadata of the product and all its images will be deleted right away, but
  /// search queries against ProductSets containing the product may still work
  /// until all related caches are refreshed.
  ///
  /// @Snippet(path: "ProductSearch_DeleteProduct")
  public func deleteProduct(
    request: DeleteProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteProduct(request: request, options: options)
  }

  /// Creates and returns a new ReferenceImage resource.
  ///
  /// The `bounding_poly` field is optional. If `bounding_poly` is not specified,
  /// the system will try to detect regions of interest in the image that are
  /// compatible with the product_category on the parent product. If it is
  /// specified, detection is ALWAYS skipped. The system converts polygons into
  /// non-rotated rectangles.
  ///
  /// Note that the pipeline will resize the image if the image resolution is too
  /// large to process (above 50MP).
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if the image_uri is missing or longer than 4096
  ///   characters.
  /// * Returns INVALID_ARGUMENT if the product does not exist.
  /// * Returns INVALID_ARGUMENT if bounding_poly is not provided, and nothing
  ///   compatible with the parent product's product_category is detected.
  /// * Returns INVALID_ARGUMENT if bounding_poly contains more than 10 polygons.
  ///
  /// @Snippet(path: "ProductSearch_CreateReferenceImage")
  public func createReferenceImage(
    request: CreateReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    try await self.inner.createReferenceImage(request: request, options: options)
  }

  /// Permanently deletes a reference image.
  ///
  /// The image metadata will be deleted right away, but search queries
  /// against ProductSets containing the image may still work until all related
  /// caches are refreshed.
  ///
  /// The actual image files are not deleted from Google Cloud Storage.
  ///
  /// @Snippet(path: "ProductSearch_DeleteReferenceImage")
  public func deleteReferenceImage(
    request: DeleteReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteReferenceImage(request: request, options: options)
  }

  /// Lists reference images.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the parent product does not exist.
  /// * Returns INVALID_ARGUMENT if the page_size is greater than 100, or less
  ///   than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListReferenceImages")
  public func listReferenceImages(
    request: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse {
    try await self.inner.listReferenceImages(request: request, options: options)
  }

  /// Lists reference images.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the parent product does not exist.
  /// * Returns INVALID_ARGUMENT if the page_size is greater than 100, or less
  ///   than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListReferenceImages")
  public func listReferenceImages(
    byItem: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReferenceImage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listReferenceImages(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information associated with a ReferenceImage.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the specified image does not exist.
  ///
  /// @Snippet(path: "ProductSearch_GetReferenceImage")
  public func getReferenceImage(
    request: GetReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    try await self.inner.getReferenceImage(request: request, options: options)
  }

  /// Adds a Product to the specified ProductSet. If the Product is already
  /// present, no change is made.
  ///
  /// One Product can be added to at most 100 ProductSets.
  ///
  /// Possible errors:
  ///
  /// * Returns NOT_FOUND if the Product or the ProductSet doesn't exist.
  ///
  /// @Snippet(path: "ProductSearch_AddProductToProductSet")
  public func addProductToProductSet(
    request: AddProductToProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.addProductToProductSet(request: request, options: options)
  }

  /// Removes a Product from the specified ProductSet.
  ///
  /// @Snippet(path: "ProductSearch_RemoveProductFromProductSet")
  public func removeProductFromProductSet(
    request: RemoveProductFromProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.removeProductFromProductSet(request: request, options: options)
  }

  /// Lists the Products in a ProductSet, in an unspecified order. If the
  /// ProductSet does not exist, the products field of the response will be
  /// empty.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100 or less than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProductsInProductSet")
  public func listProductsInProductSet(
    request: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse {
    try await self.inner.listProductsInProductSet(request: request, options: options)
  }

  /// Lists the Products in a ProductSet, in an unspecified order. If the
  /// ProductSet does not exist, the products field of the response will be
  /// empty.
  ///
  /// Possible errors:
  ///
  /// * Returns INVALID_ARGUMENT if page_size is greater than 100 or less than 1.
  ///
  /// @Snippet(path: "ProductSearch_ListProductsInProductSet")
  public func listProductsInProductSet(
    byItem: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProductsInProductSet(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Asynchronous API that imports a list of reference images to specified
  /// product sets based on a list of image information.
  ///
  /// The [google.longrunning.Operation][google.longrunning.Operation] API can be
  /// used to keep track of the progress and results of the request.
  /// `Operation.metadata` contains `BatchOperationMetadata`. (progress)
  /// `Operation.response` contains `ImportProductSetsResponse`. (results)
  ///
  /// The input source of this method is a csv file on Google Cloud Storage.
  /// For the format of the csv file please see
  /// [ImportProductSetsGcsSource.csv_file_uri][google.cloud.vision.v1.ImportProductSetsGcsSource.csv_file_uri].
  ///
  /// [google.cloud.vision.v1.ImportProductSetsGcsSource.csv_file_uri]: <doc:ImportProductSetsGcsSource/csvFileUri>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongrunning.Operation
  ///
  /// @Snippet(path: "ProductSearch_ImportProductSets")
  public func importProductSets(
    request: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.importProductSets(request: request, options: options)
  }

  /// Asynchronous API that imports a list of reference images to specified
  /// product sets based on a list of image information.
  ///
  /// The [google.longrunning.Operation][google.longrunning.Operation] API can be
  /// used to keep track of the progress and results of the request.
  /// `Operation.metadata` contains `BatchOperationMetadata`. (progress)
  /// `Operation.response` contains `ImportProductSetsResponse`. (results)
  ///
  /// The input source of this method is a csv file on Google Cloud Storage.
  /// For the format of the csv file please see
  /// [ImportProductSetsGcsSource.csv_file_uri][google.cloud.vision.v1.ImportProductSetsGcsSource.csv_file_uri].
  ///
  /// [google.cloud.vision.v1.ImportProductSetsGcsSource.csv_file_uri]: <doc:ImportProductSetsGcsSource/csvFileUri>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongrunning.Operation
  ///
  /// @Snippet(path: "ProductSearch_ImportProductSets")
  public func importProductSets(
    withPolling: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ImportProductSetsResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ImportProductSetsResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.importProductSets(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ImportProductSetsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Asynchronous API to delete all Products in a ProductSet or all Products
  /// that are in no ProductSet.
  ///
  /// If a Product is a member of the specified ProductSet in addition to other
  /// ProductSets, the Product will still be deleted.
  ///
  /// It is recommended to not delete the specified ProductSet until after this
  /// operation has completed. It is also recommended to not add any of the
  /// Products involved in the batch delete to a new ProductSet while this
  /// operation is running because those Products may still end up deleted.
  ///
  /// It's not possible to undo the PurgeProducts operation. Therefore, it is
  /// recommended to keep the csv files used in ImportProductSets (if that was
  /// how you originally built the Product Set) before starting PurgeProducts, in
  /// case you need to re-import the data after deletion.
  ///
  /// If the plan is to purge all of the Products from a ProductSet and then
  /// re-use the empty ProductSet to re-import new Products into the empty
  /// ProductSet, you must wait until the PurgeProducts operation has finished
  /// for that ProductSet.
  ///
  /// The [google.longrunning.Operation][google.longrunning.Operation] API can be
  /// used to keep track of the progress and results of the request.
  /// `Operation.metadata` contains `BatchOperationMetadata`. (progress)
  ///
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongrunning.Operation
  ///
  /// @Snippet(path: "ProductSearch_PurgeProducts")
  public func purgeProducts(
    request: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.purgeProducts(request: request, options: options)
  }

  /// Asynchronous API to delete all Products in a ProductSet or all Products
  /// that are in no ProductSet.
  ///
  /// If a Product is a member of the specified ProductSet in addition to other
  /// ProductSets, the Product will still be deleted.
  ///
  /// It is recommended to not delete the specified ProductSet until after this
  /// operation has completed. It is also recommended to not add any of the
  /// Products involved in the batch delete to a new ProductSet while this
  /// operation is running because those Products may still end up deleted.
  ///
  /// It's not possible to undo the PurgeProducts operation. Therefore, it is
  /// recommended to keep the csv files used in ImportProductSets (if that was
  /// how you originally built the Product Set) before starting PurgeProducts, in
  /// case you need to re-import the data after deletion.
  ///
  /// If the plan is to purge all of the Products from a ProductSet and then
  /// re-use the empty ProductSet to re-import new Products into the empty
  /// ProductSet, you must wait until the PurgeProducts operation has finished
  /// for that ProductSet.
  ///
  /// The [google.longrunning.Operation][google.longrunning.Operation] API can be
  /// used to keep track of the progress and results of the request.
  /// `Operation.metadata` contains `BatchOperationMetadata`. (progress)
  ///
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongrunning.Operation
  ///
  /// @Snippet(path: "ProductSearch_PurgeProducts")
  public func purgeProducts(
    withPolling: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.purgeProducts(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ProductSearch_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ProductSearchClient`.
  ///
  /// To mock `ProductSearchClient` change your functions to receive
  /// `some ProductSearchProtocol` or `any ProductSearchProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ProductSearchProtocol {
    /// See `ProductSearchClient.createProductSet`.
    func createProductSet(request: CreateProductSetRequest) async throws
      -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.createProductSet`.
    func createProductSet(
      parent: Swift.String,
      productSet: ProductSet?,
      productSetId: Swift.String,
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.listProductSets`.
    func listProductSets(request: ListProductSetsRequest) async throws
      -> GoogleCloudVisionV1.ListProductSetsResponse

    /// See `ProductSearchClient.listProductSets`.
    func listProductSets(
      byItem: ListProductSetsRequest
    ) throws -> any AsyncSequence<ProductSet, Swift.Error>

    /// See `ProductSearchClient.listProductSets`.
    func listProductSets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ProductSet, Swift.Error>

    /// See `ProductSearchClient.getProductSet`.
    func getProductSet(request: GetProductSetRequest) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.getProductSet`.
    func getProductSet(
      name: Swift.String,
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.updateProductSet`.
    func updateProductSet(request: UpdateProductSetRequest) async throws
      -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.updateProductSet`.
    func updateProductSet(
      productSet: ProductSet?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.deleteProductSet`.
    func deleteProductSet(request: DeleteProductSetRequest) async throws

    /// See `ProductSearchClient.deleteProductSet`.
    func deleteProductSet(
      name: Swift.String,
    ) async throws

    /// See `ProductSearchClient.createProduct`.
    func createProduct(request: CreateProductRequest) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.createProduct`.
    func createProduct(
      parent: Swift.String,
      product: Product?,
      productId: Swift.String,
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.listProducts`.
    func listProducts(request: ListProductsRequest) async throws
      -> GoogleCloudVisionV1.ListProductsResponse

    /// See `ProductSearchClient.listProducts`.
    func listProducts(
      byItem: ListProductsRequest
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.listProducts`.
    func listProducts(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.getProduct`.
    func getProduct(request: GetProductRequest) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.getProduct`.
    func getProduct(
      name: Swift.String,
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.updateProduct`.
    func updateProduct(request: UpdateProductRequest) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.updateProduct`.
    func updateProduct(
      product: Product?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.deleteProduct`.
    func deleteProduct(request: DeleteProductRequest) async throws

    /// See `ProductSearchClient.deleteProduct`.
    func deleteProduct(
      name: Swift.String,
    ) async throws

    /// See `ProductSearchClient.createReferenceImage`.
    func createReferenceImage(request: CreateReferenceImageRequest) async throws
      -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.createReferenceImage`.
    func createReferenceImage(
      parent: Swift.String,
      referenceImage: ReferenceImage?,
      referenceImageId: Swift.String,
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.deleteReferenceImage`.
    func deleteReferenceImage(request: DeleteReferenceImageRequest) async throws

    /// See `ProductSearchClient.deleteReferenceImage`.
    func deleteReferenceImage(
      name: Swift.String,
    ) async throws

    /// See `ProductSearchClient.listReferenceImages`.
    func listReferenceImages(request: ListReferenceImagesRequest) async throws
      -> GoogleCloudVisionV1.ListReferenceImagesResponse

    /// See `ProductSearchClient.listReferenceImages`.
    func listReferenceImages(
      byItem: ListReferenceImagesRequest
    ) throws -> any AsyncSequence<ReferenceImage, Swift.Error>

    /// See `ProductSearchClient.listReferenceImages`.
    func listReferenceImages(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ReferenceImage, Swift.Error>

    /// See `ProductSearchClient.getReferenceImage`.
    func getReferenceImage(request: GetReferenceImageRequest) async throws
      -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.getReferenceImage`.
    func getReferenceImage(
      name: Swift.String,
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.addProductToProductSet`.
    func addProductToProductSet(request: AddProductToProductSetRequest) async throws

    /// See `ProductSearchClient.addProductToProductSet`.
    func addProductToProductSet(
      name: Swift.String,
      product: Swift.String,
    ) async throws

    /// See `ProductSearchClient.removeProductFromProductSet`.
    func removeProductFromProductSet(request: RemoveProductFromProductSetRequest) async throws

    /// See `ProductSearchClient.removeProductFromProductSet`.
    func removeProductFromProductSet(
      name: Swift.String,
      product: Swift.String,
    ) async throws

    /// See `ProductSearchClient.listProductsInProductSet`.
    func listProductsInProductSet(request: ListProductsInProductSetRequest) async throws
      -> GoogleCloudVisionV1.ListProductsInProductSetResponse

    /// See `ProductSearchClient.listProductsInProductSet`.
    func listProductsInProductSet(
      byItem: ListProductsInProductSetRequest
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.listProductsInProductSet`.
    func listProductsInProductSet(
      name: Swift.String,
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.importProductSets`.
    func importProductSets(request: ImportProductSetsRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `ProductSearchClient.importProductSets`.
    func importProductSets(withPolling: ImportProductSetsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ImportProductSetsResponse>

    /// See `ProductSearchClient.importProductSets`.
    func importProductSets(
      parent: Swift.String,
      inputConfig: ImportProductSetsInputConfig?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse>

    /// See `ProductSearchClient.purgeProducts`.
    func purgeProducts(request: PurgeProductsRequest) async throws -> GoogleLongrunning.Operation

    /// See `ProductSearchClient.purgeProducts`.
    func purgeProducts(withPolling: PurgeProductsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ProductSearchClient.purgeProducts`.
    func purgeProducts(
      parent: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ProductSearchClient.createProductSet`.
    func createProductSet(
      request: CreateProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.listProductSets`.
    func listProductSets(
      request: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductSetsResponse

    /// See `ProductSearchClient.listProductSets`.
    func listProductSets(
      byItem: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ProductSet, Swift.Error>

    /// See `ProductSearchClient.getProductSet`.
    func getProductSet(
      request: GetProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.updateProductSet`.
    func updateProductSet(
      request: UpdateProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    /// See `ProductSearchClient.deleteProductSet`.
    func deleteProductSet(
      request: DeleteProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ProductSearchClient.createProduct`.
    func createProduct(
      request: CreateProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.listProducts`.
    func listProducts(
      request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsResponse

    /// See `ProductSearchClient.listProducts`.
    func listProducts(
      byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.getProduct`.
    func getProduct(
      request: GetProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.updateProduct`.
    func updateProduct(
      request: UpdateProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    /// See `ProductSearchClient.deleteProduct`.
    func deleteProduct(
      request: DeleteProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ProductSearchClient.createReferenceImage`.
    func createReferenceImage(
      request: CreateReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.deleteReferenceImage`.
    func deleteReferenceImage(
      request: DeleteReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ProductSearchClient.listReferenceImages`.
    func listReferenceImages(
      request: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse

    /// See `ProductSearchClient.listReferenceImages`.
    func listReferenceImages(
      byItem: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReferenceImage, Swift.Error>

    /// See `ProductSearchClient.getReferenceImage`.
    func getReferenceImage(
      request: GetReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    /// See `ProductSearchClient.addProductToProductSet`.
    func addProductToProductSet(
      request: AddProductToProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ProductSearchClient.removeProductFromProductSet`.
    func removeProductFromProductSet(
      request: RemoveProductFromProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ProductSearchClient.listProductsInProductSet`.
    func listProductsInProductSet(
      request: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse

    /// See `ProductSearchClient.listProductsInProductSet`.
    func listProductsInProductSet(
      byItem: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `ProductSearchClient.importProductSets`.
    func importProductSets(
      request: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ProductSearchClient.importProductSets`.
    func importProductSets(
      withPolling: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse>

    /// See `ProductSearchClient.purgeProducts`.
    func purgeProducts(
      request: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ProductSearchClient.purgeProducts`.
    func purgeProducts(
      withPolling: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>
  }
}

// Default implementations
extension Clients.ProductSearchProtocol {
  public func createProductSet(request: CreateProductSetRequest) async throws
    -> GoogleCloudVisionV1.ProductSet
  {
    try await self.createProductSet(request: request, options: .init())
  }

  public func createProductSet(
    request: CreateProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createProductSet(
    parent: Swift.String,
    productSet: ProductSet?,
    productSetId: Swift.String,
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    let request = CreateProductSetRequest().with {
      $0.parent = parent
      $0.productSet = productSet
      $0.productSetId = productSetId
    }
    return try await self.createProductSet(request: request)
  }

  public func listProductSets(request: ListProductSetsRequest) async throws
    -> GoogleCloudVisionV1.ListProductSetsResponse
  {
    try await self.listProductSets(request: request, options: .init())
  }

  public func listProductSets(
    request: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductSetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProductSets(
    byItem: ListProductSetsRequest
  ) throws -> any AsyncSequence<ProductSet, Swift.Error> {
    try self.listProductSets(byItem: byItem, options: .init())
  }

  public func listProductSets(
    byItem: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProductSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductSetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProductSets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ProductSet, Swift.Error> {
    let request = ListProductSetsRequest().with {
      $0.parent = parent
    }
    return try self.listProductSets(byItem: request)
  }

  public func getProductSet(request: GetProductSetRequest) async throws
    -> GoogleCloudVisionV1.ProductSet
  {
    try await self.getProductSet(request: request, options: .init())
  }

  public func getProductSet(
    request: GetProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProductSet(
    name: Swift.String,
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    let request = GetProductSetRequest().with {
      $0.name = name
    }
    return try await self.getProductSet(request: request)
  }

  public func updateProductSet(request: UpdateProductSetRequest) async throws
    -> GoogleCloudVisionV1.ProductSet
  {
    try await self.updateProductSet(request: request, options: .init())
  }

  public func updateProductSet(
    request: UpdateProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateProductSet(
    productSet: ProductSet?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudVisionV1.ProductSet {
    let request = UpdateProductSetRequest().with {
      $0.productSet = productSet
      $0.updateMask = updateMask
    }
    return try await self.updateProductSet(request: request)
  }

  public func deleteProductSet(request: DeleteProductSetRequest) async throws {
    try await self.deleteProductSet(request: request, options: .init())
  }

  public func deleteProductSet(
    request: DeleteProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteProductSet(
    name: Swift.String,
  ) async throws {
    let request = DeleteProductSetRequest().with {
      $0.name = name
    }
    try await self.deleteProductSet(request: request)
  }

  public func createProduct(request: CreateProductRequest) async throws
    -> GoogleCloudVisionV1.Product
  {
    try await self.createProduct(request: request, options: .init())
  }

  public func createProduct(
    request: CreateProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createProduct(
    parent: Swift.String,
    product: Product?,
    productId: Swift.String,
  ) async throws -> GoogleCloudVisionV1.Product {
    let request = CreateProductRequest().with {
      $0.parent = parent
      $0.product = product
      $0.productId = productId
    }
    return try await self.createProduct(request: request)
  }

  public func listProducts(request: ListProductsRequest) async throws
    -> GoogleCloudVisionV1.ListProductsResponse
  {
    try await self.listProducts(request: request, options: .init())
  }

  public func listProducts(
    request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProducts(
    byItem: ListProductsRequest
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    try self.listProducts(byItem: byItem, options: .init())
  }

  public func listProducts(
    byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProducts(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let request = ListProductsRequest().with {
      $0.parent = parent
    }
    return try self.listProducts(byItem: request)
  }

  public func getProduct(request: GetProductRequest) async throws -> GoogleCloudVisionV1.Product {
    try await self.getProduct(request: request, options: .init())
  }

  public func getProduct(
    request: GetProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProduct(
    name: Swift.String,
  ) async throws -> GoogleCloudVisionV1.Product {
    let request = GetProductRequest().with {
      $0.name = name
    }
    return try await self.getProduct(request: request)
  }

  public func updateProduct(request: UpdateProductRequest) async throws
    -> GoogleCloudVisionV1.Product
  {
    try await self.updateProduct(request: request, options: .init())
  }

  public func updateProduct(
    request: UpdateProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.Product {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateProduct(
    product: Product?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudVisionV1.Product {
    let request = UpdateProductRequest().with {
      $0.product = product
      $0.updateMask = updateMask
    }
    return try await self.updateProduct(request: request)
  }

  public func deleteProduct(request: DeleteProductRequest) async throws {
    try await self.deleteProduct(request: request, options: .init())
  }

  public func deleteProduct(
    request: DeleteProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteProduct(
    name: Swift.String,
  ) async throws {
    let request = DeleteProductRequest().with {
      $0.name = name
    }
    try await self.deleteProduct(request: request)
  }

  public func createReferenceImage(request: CreateReferenceImageRequest) async throws
    -> GoogleCloudVisionV1.ReferenceImage
  {
    try await self.createReferenceImage(request: request, options: .init())
  }

  public func createReferenceImage(
    request: CreateReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createReferenceImage(
    parent: Swift.String,
    referenceImage: ReferenceImage?,
    referenceImageId: Swift.String,
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    let request = CreateReferenceImageRequest().with {
      $0.parent = parent
      $0.referenceImage = referenceImage
      $0.referenceImageId = referenceImageId
    }
    return try await self.createReferenceImage(request: request)
  }

  public func deleteReferenceImage(request: DeleteReferenceImageRequest) async throws {
    try await self.deleteReferenceImage(request: request, options: .init())
  }

  public func deleteReferenceImage(
    request: DeleteReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteReferenceImage(
    name: Swift.String,
  ) async throws {
    let request = DeleteReferenceImageRequest().with {
      $0.name = name
    }
    try await self.deleteReferenceImage(request: request)
  }

  public func listReferenceImages(request: ListReferenceImagesRequest) async throws
    -> GoogleCloudVisionV1.ListReferenceImagesResponse
  {
    try await self.listReferenceImages(request: request, options: .init())
  }

  public func listReferenceImages(
    request: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReferenceImages(
    byItem: ListReferenceImagesRequest
  ) throws -> any AsyncSequence<ReferenceImage, Swift.Error> {
    try self.listReferenceImages(byItem: byItem, options: .init())
  }

  public func listReferenceImages(
    byItem: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReferenceImage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReferenceImages(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReferenceImage, Swift.Error> {
    let request = ListReferenceImagesRequest().with {
      $0.parent = parent
    }
    return try self.listReferenceImages(byItem: request)
  }

  public func getReferenceImage(request: GetReferenceImageRequest) async throws
    -> GoogleCloudVisionV1.ReferenceImage
  {
    try await self.getReferenceImage(request: request, options: .init())
  }

  public func getReferenceImage(
    request: GetReferenceImageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReferenceImage(
    name: Swift.String,
  ) async throws -> GoogleCloudVisionV1.ReferenceImage {
    let request = GetReferenceImageRequest().with {
      $0.name = name
    }
    return try await self.getReferenceImage(request: request)
  }

  public func addProductToProductSet(request: AddProductToProductSetRequest) async throws {
    try await self.addProductToProductSet(request: request, options: .init())
  }

  public func addProductToProductSet(
    request: AddProductToProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func addProductToProductSet(
    name: Swift.String,
    product: Swift.String,
  ) async throws {
    let request = AddProductToProductSetRequest().with {
      $0.name = name
      $0.product = product
    }
    try await self.addProductToProductSet(request: request)
  }

  public func removeProductFromProductSet(request: RemoveProductFromProductSetRequest) async throws
  {
    try await self.removeProductFromProductSet(request: request, options: .init())
  }

  public func removeProductFromProductSet(
    request: RemoveProductFromProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func removeProductFromProductSet(
    name: Swift.String,
    product: Swift.String,
  ) async throws {
    let request = RemoveProductFromProductSetRequest().with {
      $0.name = name
      $0.product = product
    }
    try await self.removeProductFromProductSet(request: request)
  }

  public func listProductsInProductSet(request: ListProductsInProductSetRequest) async throws
    -> GoogleCloudVisionV1.ListProductsInProductSetResponse
  {
    try await self.listProductsInProductSet(request: request, options: .init())
  }

  public func listProductsInProductSet(
    request: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProductsInProductSet(
    byItem: ListProductsInProductSetRequest
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    try self.listProductsInProductSet(byItem: byItem, options: .init())
  }

  public func listProductsInProductSet(
    byItem: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProductsInProductSet(
    name: Swift.String,
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let request = ListProductsInProductSetRequest().with {
      $0.name = name
    }
    return try self.listProductsInProductSet(byItem: request)
  }

  public func importProductSets(request: ImportProductSetsRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.importProductSets(request: request, options: .init())
  }

  public func importProductSets(
    request: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importProductSets(withPolling: ImportProductSetsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse>
  {
    try await self.importProductSets(withPolling: withPolling, options: .init())
  }

  public func importProductSets(
    withPolling: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ImportProductSetsResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func importProductSets(
    parent: Swift.String,
    inputConfig: ImportProductSetsInputConfig?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ImportProductSetsResponse> {
    let request = ImportProductSetsRequest().with {
      $0.parent = parent
      $0.inputConfig = inputConfig
    }
    return try await self.importProductSets(withPolling: request)
  }

  public func purgeProducts(request: PurgeProductsRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.purgeProducts(request: request, options: .init())
  }

  public func purgeProducts(
    request: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func purgeProducts(withPolling: PurgeProductsRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.purgeProducts(withPolling: withPolling, options: .init())
  }

  public func purgeProducts(
    withPolling: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func purgeProducts(
    parent: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = PurgeProductsRequest().with {
      $0.parent = parent
    }
    return try await self.purgeProducts(withPolling: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
