// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Results for a product search request.
public struct ProductSearchResults: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Timestamp of the index which provided these results. Products added to the
  /// product set and products removed from the product set after this time are
  /// not reflected in the current results.
  public var indexTime: GoogleCloudWkt.Timestamp? = nil

  /// List of results, one for each product match.
  public var results: [ProductSearchResults.Result] = []

  /// List of results grouped by products detected in the query image. Each entry
  /// corresponds to one bounding polygon in the query image, and contains the
  /// matching products specific to that region. There may be duplicate product
  /// matches in the union of all the per-product results.
  public var productGroupedResults: [ProductSearchResults.GroupedResult] = []

  /// Initialize a new instance of `ProductSearchResults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProductSearchResults().with { $0.indexTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information about a product.
  public struct Result: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The Product.
    public var product: Product? = nil

    /// A confidence level on the match, ranging from 0 (no confidence) to
    /// 1 (full confidence).
    public var score: Swift.Float = Swift.Float()

    /// The resource name of the image from the product that is the closest match
    /// to the query.
    public var image: Swift.String = Swift.String()

    /// Initialize a new instance of `Result`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Result().with { $0.product = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.Result"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Prediction for what the object in the bounding box is.
  public struct ObjectAnnotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Object ID that should align with EntityAnnotation mid.
    public var mid: Swift.String = Swift.String()

    /// The BCP-47 language code, such as "en-US" or "sr-Latn". For more
    /// information, see
    /// http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
    public var languageCode: Swift.String = Swift.String()

    /// Object name, expressed in its `language_code` language.
    public var name: Swift.String = Swift.String()

    /// Score of the result. Range [0, 1].
    public var score: Swift.Float = Swift.Float()

    /// Initialize a new instance of `ObjectAnnotation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ObjectAnnotation().with { $0.mid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Information about the products similar to a single product in a query
  /// image.
  public struct GroupedResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The bounding polygon around the product detected in the query image.
    public var boundingPoly: BoundingPoly? = nil

    /// List of results, one for each product match.
    public var results: [ProductSearchResults.Result] = []

    /// List of generic predictions for the object in the bounding box.
    public var objectAnnotations: [ProductSearchResults.ObjectAnnotation] = []

    /// Initialize a new instance of `GroupedResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GroupedResult().with { $0.boundingPoly = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.GroupedResult"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
