// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Results for a product search request.
public struct ProductSearchResults: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Timestamp of the index which provided these results. Products added to the
  /// product set and products removed from the product set after this time are
  /// not reflected in the current results.
  public var indexTime: GoogleWKT.WKTTimestamp? = nil

  /// List of results, one for each product match.
  public var results: [ProductSearchResults.Result] = []

  /// List of results grouped by products detected in the query image. Each entry
  /// corresponds to one bounding polygon in the query image, and contains the
  /// matching products specific to that region. There may be duplicate product
  /// matches in the union of all the per-product results.
  public var productGroupedResults: [ProductSearchResults.GroupedResult] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProductSearchResults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProductSearchResults().with { $0.indexTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let indexTime = CodingKeys(stringValue: "indexTime")
    static let results = CodingKeys(stringValue: "results")
    static let productGroupedResults = CodingKeys(stringValue: "productGroupedResults")

    static let _knownKeys: Set<Swift.String> = [
      "indexTime",
      "results",
      "productGroupedResults",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.indexTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .indexTime)
    if let value = try container.decodeIfPresent(
      [ProductSearchResults.Result].self, forKey: .results)
    {
      self.results = value
    }
    if let value = try container.decodeIfPresent(
      [ProductSearchResults.GroupedResult].self, forKey: .productGroupedResults)
    {
      self.productGroupedResults = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.indexTime, forKey: .indexTime)
    try container.encode(self.results, forKey: .results)
    try container.encode(self.productGroupedResults, forKey: .productGroupedResults)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Information about a product.
  public struct Result: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Product.
    public var product: Product? = nil

    /// A confidence level on the match, ranging from 0 (no confidence) to
    /// 1 (full confidence).
    public var score: Swift.Float = Swift.Float()

    /// The resource name of the image from the product that is the closest match
    /// to the query.
    public var image: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Result`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Result().with { $0.product = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let product = CodingKeys(stringValue: "product")
      static let score = CodingKeys(stringValue: "score")
      static let image = CodingKeys(stringValue: "image")

      static let _knownKeys: Set<Swift.String> = [
        "product",
        "score",
        "image",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.product = try container.decodeIfPresent(Product.self, forKey: .product)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .image) {
        self.image = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.product, forKey: .product)
      try container.encode(self.score, forKey: .score)
      try container.encode(self.image, forKey: .image)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.Result"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Prediction for what the object in the bounding box is.
  public struct ObjectAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Object ID that should align with EntityAnnotation mid.
    public var mid: Swift.String = Swift.String()

    /// The BCP-47 language code, such as "en-US" or "sr-Latn". For more
    /// information, see
    /// http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
    public var languageCode: Swift.String = Swift.String()

    /// Object name, expressed in its `language_code` language.
    public var name: Swift.String = Swift.String()

    /// Score of the result. Range [0, 1].
    public var score: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ObjectAnnotation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ObjectAnnotation().with { $0.mid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let mid = CodingKeys(stringValue: "mid")
      static let languageCode = CodingKeys(stringValue: "languageCode")
      static let name = CodingKeys(stringValue: "name")
      static let score = CodingKeys(stringValue: "score")

      static let _knownKeys: Set<Swift.String> = [
        "mid",
        "languageCode",
        "name",
        "score",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mid) {
        self.mid = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
        self.languageCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.mid, forKey: .mid)
      try container.encode(self.languageCode, forKey: .languageCode)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.score, forKey: .score)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about the products similar to a single product in a query
  /// image.
  public struct GroupedResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The bounding polygon around the product detected in the query image.
    public var boundingPoly: BoundingPoly? = nil

    /// List of results, one for each product match.
    public var results: [ProductSearchResults.Result] = []

    /// List of generic predictions for the object in the bounding box.
    public var objectAnnotations: [ProductSearchResults.ObjectAnnotation] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GroupedResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GroupedResult().with { $0.boundingPoly = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let boundingPoly = CodingKeys(stringValue: "boundingPoly")
      static let results = CodingKeys(stringValue: "results")
      static let objectAnnotations = CodingKeys(stringValue: "objectAnnotations")

      static let _knownKeys: Set<Swift.String> = [
        "boundingPoly",
        "results",
        "objectAnnotations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.boundingPoly = try container.decodeIfPresent(BoundingPoly.self, forKey: .boundingPoly)
      if let value = try container.decodeIfPresent(
        [ProductSearchResults.Result].self, forKey: .results)
      {
        self.results = value
      }
      if let value = try container.decodeIfPresent(
        [ProductSearchResults.ObjectAnnotation].self, forKey: .objectAnnotations)
      {
        self.objectAnnotations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.boundingPoly, forKey: .boundingPoly)
      try container.encode(self.results, forKey: .results)
      try container.encode(self.objectAnnotations, forKey: .objectAnnotations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults.GroupedResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ProductSearchResults"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
