// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Product contains ReferenceImages.
public struct Product: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the product.
  ///
  /// Format is:
  /// `projects/PROJECT_ID/locations/LOC_ID/products/PRODUCT_ID`.
  ///
  /// This field is ignored when creating a product.
  public var name: Swift.String = Swift.String()

  /// The user-provided name for this Product. Must not be empty. Must be at most
  /// 4096 characters long.
  public var displayName: Swift.String = Swift.String()

  /// User-provided metadata to be stored with this product. Must be at most 4096
  /// characters long.
  public var description: Swift.String = Swift.String()

  /// Immutable. The category for the product identified by the reference image.
  /// This should be one of "homegoods-v2", "apparel-v2", "toys-v2",
  /// "packagedgoods-v1" or "general-v1". The legacy categories "homegoods",
  /// "apparel", and "toys" are still supported, but these should not be used for
  /// new products.
  public var productCategory: Swift.String = Swift.String()

  /// Key-value pairs that can be attached to a product. At query time,
  /// constraints can be specified based on the product_labels.
  ///
  /// Note that integer values can be provided as strings, e.g. "1199". Only
  /// strings with integer values can match a range-based restriction which is
  /// to be supported soon.
  ///
  /// Multiple values can be assigned to the same key. One product may have up to
  /// 500 product_labels.
  ///
  /// Notice that the total number of distinct product_labels over all products
  /// in one ProductSet cannot exceed 1M, otherwise the product search pipeline
  /// will refuse to work for that ProductSet.
  public var productLabels: [Product.KeyValue] = []

  /// Initialize a new instance of `Product`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Product().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A product label represented as a key-value pair.
  public struct KeyValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The key of the label attached to the product. Cannot be empty and cannot
    /// exceed 128 bytes.
    public var key: Swift.String = Swift.String()

    /// The value of the label attached to the product. Cannot be empty and
    /// cannot exceed 128 bytes.
    public var value: Swift.String = Swift.String()

    /// Initialize a new instance of `KeyValue`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KeyValue().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.Product.KeyValue"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.Product"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
