// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ProductSearchStub: Sendable {
    func createProductSet(
      request: CreateProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    func listProductSets(
      request: ListProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductSetsResponse

    func getProductSet(
      request: GetProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    func updateProductSet(
      request: UpdateProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ProductSet

    func deleteProductSet(
      request: DeleteProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createProduct(
      request: CreateProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    func listProducts(
      request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsResponse

    func getProduct(
      request: GetProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    func updateProduct(
      request: UpdateProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.Product

    func deleteProduct(
      request: DeleteProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createReferenceImage(
      request: CreateReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    func deleteReferenceImage(
      request: DeleteReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listReferenceImages(
      request: ListReferenceImagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListReferenceImagesResponse

    func getReferenceImage(
      request: GetReferenceImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ReferenceImage

    func addProductToProductSet(
      request: AddProductToProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func removeProductFromProductSet(
      request: RemoveProductFromProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listProductsInProductSet(
      request: ListProductsInProductSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVisionV1.ListProductsInProductSetResponse

    func importProductSets(
      request: ImportProductSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func purgeProducts(
      request: PurgeProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
