// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// A ProductSet contains Products. A ProductSet can contain a maximum of 1
/// million reference images. If the limit is exceeded, periodic indexing will
/// fail.
public struct ProductSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the ProductSet.
  ///
  /// Format is:
  /// `projects/PROJECT_ID/locations/LOC_ID/productSets/PRODUCT_SET_ID`.
  ///
  /// This field is ignored when creating a ProductSet.
  public var name: Swift.String = Swift.String()

  /// The user-provided name for this ProductSet. Must not be empty. Must be at
  /// most 4096 characters long.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The time at which this ProductSet was last indexed. Query
  /// results will reflect all updates before this time. If this ProductSet has
  /// never been indexed, this timestamp is the default value
  /// "1970-01-01T00:00:00Z".
  ///
  /// This field is ignored when creating a ProductSet.
  public var indexTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. If there was an error with indexing the product set, the field
  /// is populated.
  ///
  /// This field is ignored when creating a ProductSet.
  public var indexError: GoogleRpc.Status? = nil

  /// Initialize a new instance of `ProductSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProductSet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ProductSet"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
