// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Parameters for a product search request.
public struct ProductSearchParams: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The bounding polygon around the area of interest in the image.
  /// If it is not specified, system discretion will be applied.
  public var boundingPoly: BoundingPoly? = nil

  /// The resource name of a [ProductSet][google.cloud.vision.v1.ProductSet] to
  /// be searched for similar images.
  ///
  /// Format is:
  /// `projects/PROJECT_ID/locations/LOC_ID/productSets/PRODUCT_SET_ID`.
  ///
  /// [google.cloud.vision.v1.ProductSet]: <doc:ProductSet>
  public var productSet: Swift.String = Swift.String()

  /// The list of product categories to search in. Currently, we only consider
  /// the first category, and either "homegoods-v2", "apparel-v2", "toys-v2",
  /// "packagedgoods-v1", or "general-v1" should be specified. The legacy
  /// categories "homegoods", "apparel", and "toys" are still supported but will
  /// be deprecated. For new products, please use "homegoods-v2", "apparel-v2",
  /// or "toys-v2" for better product search accuracy. It is recommended to
  /// migrate existing products to these categories as well.
  public var productCategories: [Swift.String] = []

  /// The filtering expression. This can be used to restrict search results based
  /// on Product labels. We currently support an AND of OR of key-value
  /// expressions, where each expression within an OR must have the same key. An
  /// '=' should be used to connect the key and value.
  ///
  /// For example, "(color = red OR color = blue) AND brand = Google" is
  /// acceptable, but "(color = red OR brand = Google)" is not acceptable.
  /// "color: red" is not acceptable because it uses a ':' instead of an '='.
  public var filter: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProductSearchParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProductSearchParams().with { $0.boundingPoly = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let boundingPoly = CodingKeys(stringValue: "boundingPoly")
    static let productSet = CodingKeys(stringValue: "productSet")
    static let productCategories = CodingKeys(stringValue: "productCategories")
    static let filter = CodingKeys(stringValue: "filter")

    static let _knownKeys: Set<Swift.String> = [
      "boundingPoly",
      "productSet",
      "productCategories",
      "filter",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.boundingPoly = try container.decodeIfPresent(BoundingPoly.self, forKey: .boundingPoly)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .productSet) {
      self.productSet = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .productCategories) {
      self.productCategories = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.boundingPoly, forKey: .boundingPoly)
    try container.encode(self.productSet, forKey: .productSet)
    try container.encode(self.productCategories, forKey: .productCategories)
    try container.encode(self.filter, forKey: .filter)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ProductSearchParams"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
