// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the `PurgeProducts` method.
public struct PurgeProductsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location in which the Products should be deleted.
  ///
  /// Format is `projects/PROJECT_ID/locations/LOC_ID`.
  public var parent: Swift.String = Swift.String()

  /// The default value is false. Override this value to true to actually perform
  /// the purge.
  public var force: Swift.Bool = Swift.Bool()

  /// The Products to delete.
  public var target: OneOf_Target? = nil

  /// Initialize a new instance of `PurgeProductsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PurgeProductsRequest().with { $0.productSetPurgeConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case productSetPurgeConfig = "productSetPurgeConfig"
    case deleteOrphanProducts = "deleteOrphanProducts"
    case parent = "parent"
    case force = "force"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.force = try container.decode(Swift.Bool.self, forKey: .force)

    var target: OneOf_Target? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let productSetPurgeConfig = try container.decodeIfPresent(
      ProductSetPurgeConfig?.self, forKey: .productSetPurgeConfig)
    {
      try targetCheckAndSet(.productSetPurgeConfig(productSetPurgeConfig))
    }
    if let deleteOrphanProducts = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deleteOrphanProducts)
    {
      try targetCheckAndSet(.deleteOrphanProducts(deleteOrphanProducts))
    }
    self.target = target
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.force, forKey: .force)

    if let choice = self.target {
      switch choice {
      case .productSetPurgeConfig(let value):
        try container.encode(value, forKey: .productSetPurgeConfig)
      case .deleteOrphanProducts(let value):
        try container.encode(value, forKey: .deleteOrphanProducts)
      }
    }
  }

  /// The Products to delete.
  public enum OneOf_Target: Codable, Equatable, Sendable {
    /// Specify which ProductSet contains the Products to be deleted.
    indirect case productSetPurgeConfig(ProductSetPurgeConfig?)
    /// If delete_orphan_products is true, all Products that are not in any
    /// ProductSet will be deleted.
    case deleteOrphanProducts(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.PurgeProductsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
