// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A `ReferenceImage` represents a product image and its associated metadata,
/// such as bounding boxes.
public struct ReferenceImage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the reference image.
  ///
  /// Format is:
  /// `projects/PROJECT_ID/locations/LOC_ID/products/PRODUCT_ID/referenceImages/IMAGE_ID`.
  ///
  /// This field is ignored when creating a reference image.
  public var name: Swift.String = Swift.String()

  /// Required. The Google Cloud Storage URI of the reference image.
  ///
  /// The URI must start with `gs://`.
  public var uri: Swift.String = Swift.String()

  /// Optional. Bounding polygons around the areas of interest in the reference
  /// image. If this field is empty, the system will try to detect regions of
  /// interest. At most 10 bounding polygons will be used.
  ///
  /// The provided shape is converted into a non-rotated rectangle. Once
  /// converted, the small edge of the rectangle must be greater than or equal
  /// to 300 pixels. The aspect ratio must be 1:4 or less (i.e. 1:3 is ok; 1:5
  /// is not).
  public var boundingPolys: [BoundingPoly] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReferenceImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReferenceImage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uri = CodingKeys(stringValue: "uri")
    static let boundingPolys = CodingKeys(stringValue: "boundingPolys")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uri",
      "boundingPolys",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent([BoundingPoly].self, forKey: .boundingPolys) {
      self.boundingPolys = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.boundingPolys, forKey: .boundingPolys)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.ReferenceImage"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
