// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Set of features pertaining to the image, computed by computer vision
/// methods over safe-search verticals (for example, adult, spoof, medical,
/// violence).
public struct SafeSearchAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Represents the adult content likelihood for the image. Adult content may
  /// contain elements such as nudity, pornographic images or cartoons, or
  /// sexual activities.
  public var adult: Likelihood = Likelihood()

  /// Spoof likelihood. The likelihood that an modification
  /// was made to the image's canonical version to make it appear
  /// funny or offensive.
  public var spoof: Likelihood = Likelihood()

  /// Likelihood that this is a medical image.
  public var medical: Likelihood = Likelihood()

  /// Likelihood that this image contains violent content. Violent content may
  /// include death, serious harm, or injury to individuals or groups of
  /// individuals.
  public var violence: Likelihood = Likelihood()

  /// Likelihood that the request image contains racy content. Racy content may
  /// include (but is not limited to) skimpy or sheer clothing, strategically
  /// covered nudity, lewd or provocative poses, or close-ups of sensitive
  /// body areas.
  public var racy: Likelihood = Likelihood()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SafeSearchAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SafeSearchAnnotation().with { $0.adult = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let adult = CodingKeys(stringValue: "adult")
    static let spoof = CodingKeys(stringValue: "spoof")
    static let medical = CodingKeys(stringValue: "medical")
    static let violence = CodingKeys(stringValue: "violence")
    static let racy = CodingKeys(stringValue: "racy")

    static let _knownKeys: Set<Swift.String> = [
      "adult",
      "spoof",
      "medical",
      "violence",
      "racy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .adult) {
      self.adult = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .spoof) {
      self.spoof = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .medical) {
      self.medical = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .violence) {
      self.violence = value
    }
    if let value = try container.decodeIfPresent(Likelihood.self, forKey: .racy) {
      self.racy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.adult, forKey: .adult)
    try container.encode(self.spoof, forKey: .spoof)
    try container.encode(self.medical, forKey: .medical)
    try container.encode(self.violence, forKey: .violence)
    try container.encode(self.racy, forKey: .racy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.SafeSearchAnnotation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
