// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// TextAnnotation contains a structured representation of OCR extracted text.
/// The hierarchy of an OCR extracted text structure is like this:
///     TextAnnotation -> Page -> Block -> Paragraph -> Word -> Symbol
/// Each structural component, starting from Page, may further have their own
/// properties. Properties describe detected languages, breaks etc.. Please refer
/// to the
/// [TextAnnotation.TextProperty][google.cloud.vision.v1.TextAnnotation.TextProperty]
/// message definition below for more detail.
///
/// [google.cloud.vision.v1.TextAnnotation.TextProperty]: <doc:TextAnnotation/TextProperty>
public struct TextAnnotation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// List of pages detected by OCR.
  public var pages: [Page] = []

  /// UTF-8 text detected on the pages.
  public var text: Swift.String = Swift.String()

  /// Initialize a new instance of `TextAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TextAnnotation().with { $0.pages = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Detected language for a structural component.
  public struct DetectedLanguage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The BCP-47 language code, such as "en-US" or "sr-Latn". For more
    /// information, see
    /// http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
    public var languageCode: Swift.String = Swift.String()

    /// Confidence of detected language. Range [0, 1].
    public var confidence: Swift.Float = Swift.Float()

    /// Initialize a new instance of `DetectedLanguage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedLanguage().with { $0.languageCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.TextAnnotation.DetectedLanguage"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Detected start or end of a structural component.
  public struct DetectedBreak: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Detected break type.
    public var type: TextAnnotation.DetectedBreak.BreakType = TextAnnotation.DetectedBreak
      .BreakType()

    /// True if break prepends the element.
    public var isPrefix: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `DetectedBreak`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedBreak().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Enum to denote the type of break found. New line, space etc.
    public enum BreakType: Codable, Equatable, Sendable {
      /// Unknown break label type.
      case unknown
      /// Regular space.
      case space
      /// Sure space (very wide).
      case sureSpace
      /// Line-wrapping break.
      case eolSureSpace
      /// End-line hyphen that is not present in text; does not co-occur with
      /// `SPACE`, `LEADER_SPACE`, or `LINE_BREAK`.
      case hyphen
      /// Line break that ends a paragraph.
      case lineBreak
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unknown
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unknown: return 0
        case .space: return 1
        case .sureSpace: return 2
        case .eolSureSpace: return 3
        case .hyphen: return 4
        case .lineBreak: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unknown: return "UNKNOWN"
        case .space: return "SPACE"
        case .sureSpace: return "SURE_SPACE"
        case .eolSureSpace: return "EOL_SURE_SPACE"
        case .hyphen: return "HYPHEN"
        case .lineBreak: return "LINE_BREAK"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BreakType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "UNKNOWN": self = .unknown
        case "SPACE": self = .space
        case "SURE_SPACE": self = .sureSpace
        case "EOL_SURE_SPACE": self = .eolSureSpace
        case "HYPHEN": self = .hyphen
        case "LINE_BREAK": self = .lineBreak
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BreakType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unknown
        case 1: self = .space
        case 2: self = .sureSpace
        case 3: self = .eolSureSpace
        case 4: self = .hyphen
        case 5: self = .lineBreak
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unknown: return try container.encode(0)
        case .space: return try container.encode(1)
        case .sureSpace: return try container.encode(2)
        case .eolSureSpace: return try container.encode(3)
        case .hyphen: return try container.encode(4)
        case .lineBreak: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.TextAnnotation.DetectedBreak"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Additional information detected on the structural component.
  public struct TextProperty: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A list of detected languages together with confidence.
    public var detectedLanguages: [TextAnnotation.DetectedLanguage] = []

    /// Detected start or end of a text segment.
    public var detectedBreak: TextAnnotation.DetectedBreak? = nil

    /// Initialize a new instance of `TextProperty`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TextProperty().with { $0.detectedLanguages = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.TextAnnotation.TextProperty"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.TextAnnotation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
