// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Parameters for text detections. This is used to control TEXT_DETECTION and
/// DOCUMENT_TEXT_DETECTION features.
public struct TextDetectionParams: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// By default, Cloud Vision API only includes confidence score for
  /// DOCUMENT_TEXT_DETECTION result. Set the flag to true to include confidence
  /// score for TEXT_DETECTION as well.
  public var enableTextDetectionConfidenceScore: Swift.Bool = Swift.Bool()

  /// A list of advanced OCR options to further fine-tune OCR behavior.
  /// Current valid values are:
  ///
  /// - `legacy_layout`: a heuristics layout detection algorithm, which serves as
  /// an alternative to the current ML-based layout detection algorithm.
  /// Customers can choose the best suitable layout algorithm based on their
  /// situation.
  public var advancedOcrOptions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TextDetectionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TextDetectionParams().with { $0.enableTextDetectionConfidenceScore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableTextDetectionConfidenceScore = CodingKeys(
      stringValue: "enableTextDetectionConfidenceScore")
    static let advancedOcrOptions = CodingKeys(stringValue: "advancedOcrOptions")

    static let _knownKeys: Set<Swift.String> = [
      "enableTextDetectionConfidenceScore",
      "advancedOcrOptions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableTextDetectionConfidenceScore)
    {
      self.enableTextDetectionConfidenceScore = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .advancedOcrOptions) {
      self.advancedOcrOptions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.enableTextDetectionConfidenceScore, forKey: .enableTextDetectionConfidenceScore)
    try container.encode(self.advancedOcrOptions, forKey: .advancedOcrOptions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.TextDetectionParams"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
