// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Parameters for text detections. This is used to control TEXT_DETECTION and
/// DOCUMENT_TEXT_DETECTION features.
public struct TextDetectionParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// By default, Cloud Vision API only includes confidence score for
  /// DOCUMENT_TEXT_DETECTION result. Set the flag to true to include confidence
  /// score for TEXT_DETECTION as well.
  public var enableTextDetectionConfidenceScore: Swift.Bool = Swift.Bool()

  /// A list of advanced OCR options to further fine-tune OCR behavior.
  /// Current valid values are:
  ///
  /// - `legacy_layout`: a heuristics layout detection algorithm, which serves as
  /// an alternative to the current ML-based layout detection algorithm.
  /// Customers can choose the best suitable layout algorithm based on their
  /// situation.
  public var advancedOcrOptions: [Swift.String] = []

  /// Initialize a new instance of `TextDetectionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TextDetectionParams().with { $0.enableTextDetectionConfidenceScore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.vision.v1.TextDetectionParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
