// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Relevant information for the image from the Internet.
public struct WebDetection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Deduced entities from similar images on the Internet.
  public var webEntities: [WebDetection.WebEntity] = []

  /// Fully matching images from the Internet.
  /// Can include resized copies of the query image.
  public var fullMatchingImages: [WebDetection.WebImage] = []

  /// Partial matching images from the Internet.
  /// Those images are similar enough to share some key-point features. For
  /// example an original image will likely have partial matching for its crops.
  public var partialMatchingImages: [WebDetection.WebImage] = []

  /// Web pages containing the matching images from the Internet.
  public var pagesWithMatchingImages: [WebDetection.WebPage] = []

  /// The visually similar image results.
  public var visuallySimilarImages: [WebDetection.WebImage] = []

  /// The service's best guess as to the topic of the request image.
  /// Inferred from similar images on the open web.
  public var bestGuessLabels: [WebDetection.WebLabel] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WebDetection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WebDetection().with { $0.webEntities = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let webEntities = CodingKeys(stringValue: "webEntities")
    static let fullMatchingImages = CodingKeys(stringValue: "fullMatchingImages")
    static let partialMatchingImages = CodingKeys(stringValue: "partialMatchingImages")
    static let pagesWithMatchingImages = CodingKeys(stringValue: "pagesWithMatchingImages")
    static let visuallySimilarImages = CodingKeys(stringValue: "visuallySimilarImages")
    static let bestGuessLabels = CodingKeys(stringValue: "bestGuessLabels")

    static let _knownKeys: Set<Swift.String> = [
      "webEntities",
      "fullMatchingImages",
      "partialMatchingImages",
      "pagesWithMatchingImages",
      "visuallySimilarImages",
      "bestGuessLabels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [WebDetection.WebEntity].self, forKey: .webEntities)
    {
      self.webEntities = value
    }
    if let value = try container.decodeIfPresent(
      [WebDetection.WebImage].self, forKey: .fullMatchingImages)
    {
      self.fullMatchingImages = value
    }
    if let value = try container.decodeIfPresent(
      [WebDetection.WebImage].self, forKey: .partialMatchingImages)
    {
      self.partialMatchingImages = value
    }
    if let value = try container.decodeIfPresent(
      [WebDetection.WebPage].self, forKey: .pagesWithMatchingImages)
    {
      self.pagesWithMatchingImages = value
    }
    if let value = try container.decodeIfPresent(
      [WebDetection.WebImage].self, forKey: .visuallySimilarImages)
    {
      self.visuallySimilarImages = value
    }
    if let value = try container.decodeIfPresent(
      [WebDetection.WebLabel].self, forKey: .bestGuessLabels)
    {
      self.bestGuessLabels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.webEntities, forKey: .webEntities)
    try container.encode(self.fullMatchingImages, forKey: .fullMatchingImages)
    try container.encode(self.partialMatchingImages, forKey: .partialMatchingImages)
    try container.encode(self.pagesWithMatchingImages, forKey: .pagesWithMatchingImages)
    try container.encode(self.visuallySimilarImages, forKey: .visuallySimilarImages)
    try container.encode(self.bestGuessLabels, forKey: .bestGuessLabels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Entity deduced from similar images on the Internet.
  public struct WebEntity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Opaque entity ID.
    public var entityId: Swift.String = Swift.String()

    /// Overall relevancy score for the entity.
    /// Not normalized and not comparable across different image queries.
    public var score: Swift.Float = Swift.Float()

    /// Canonical description of the entity, in English.
    public var description: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WebEntity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebEntity().with { $0.entityId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let entityId = CodingKeys(stringValue: "entityId")
      static let score = CodingKeys(stringValue: "score")
      static let description = CodingKeys(stringValue: "description")

      static let _knownKeys: Set<Swift.String> = [
        "entityId",
        "score",
        "description",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entityId) {
        self.entityId = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.entityId, forKey: .entityId)
      try container.encode(self.score, forKey: .score)
      try container.encode(self.description, forKey: .description)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.WebDetection.WebEntity"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata for online images.
  public struct WebImage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The result image URL.
    public var url: Swift.String = Swift.String()

    /// (Deprecated) Overall relevancy score for the image.
    public var score: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WebImage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebImage().with { $0.url = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let url = CodingKeys(stringValue: "url")
      static let score = CodingKeys(stringValue: "score")

      static let _knownKeys: Set<Swift.String> = [
        "url",
        "score",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
        self.url = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.url, forKey: .url)
      try container.encode(self.score, forKey: .score)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.WebDetection.WebImage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata for web pages.
  public struct WebPage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The result web page URL.
    public var url: Swift.String = Swift.String()

    /// (Deprecated) Overall relevancy score for the web page.
    public var score: Swift.Float = Swift.Float()

    /// Title for the web page, may contain HTML markups.
    public var pageTitle: Swift.String = Swift.String()

    /// Fully matching images on the page.
    /// Can include resized copies of the query image.
    public var fullMatchingImages: [WebDetection.WebImage] = []

    /// Partial matching images on the page.
    /// Those images are similar enough to share some key-point features. For
    /// example an original image will likely have partial matching for its
    /// crops.
    public var partialMatchingImages: [WebDetection.WebImage] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WebPage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebPage().with { $0.url = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let url = CodingKeys(stringValue: "url")
      static let score = CodingKeys(stringValue: "score")
      static let pageTitle = CodingKeys(stringValue: "pageTitle")
      static let fullMatchingImages = CodingKeys(stringValue: "fullMatchingImages")
      static let partialMatchingImages = CodingKeys(stringValue: "partialMatchingImages")

      static let _knownKeys: Set<Swift.String> = [
        "url",
        "score",
        "pageTitle",
        "fullMatchingImages",
        "partialMatchingImages",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
        self.url = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageTitle) {
        self.pageTitle = value
      }
      if let value = try container.decodeIfPresent(
        [WebDetection.WebImage].self, forKey: .fullMatchingImages)
      {
        self.fullMatchingImages = value
      }
      if let value = try container.decodeIfPresent(
        [WebDetection.WebImage].self, forKey: .partialMatchingImages)
      {
        self.partialMatchingImages = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.url, forKey: .url)
      try container.encode(self.score, forKey: .score)
      try container.encode(self.pageTitle, forKey: .pageTitle)
      try container.encode(self.fullMatchingImages, forKey: .fullMatchingImages)
      try container.encode(self.partialMatchingImages, forKey: .partialMatchingImages)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.WebDetection.WebPage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Label to provide extra metadata for the web detection.
  public struct WebLabel: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Label for extra metadata.
    public var label: Swift.String = Swift.String()

    /// The BCP-47 language code for `label`, such as "en-US" or "sr-Latn".
    /// For more information, see
    /// http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
    public var languageCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WebLabel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebLabel().with { $0.label = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let label = CodingKeys(stringValue: "label")
      static let languageCode = CodingKeys(stringValue: "languageCode")

      static let _knownKeys: Set<Swift.String> = [
        "label",
        "languageCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .label) {
        self.label = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
        self.languageCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.label, forKey: .label)
      try container.encode(self.languageCode, forKey: .languageCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vision.v1.WebDetection.WebLabel"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vision.v1.WebDetection"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
